### ISSUE TITLE
Fix faraday ssl certificates in windows

### ISSUE THREAD

**Issue by eVanilla** [atipugin/telegram-bot-ruby#101]
in windows you should get same error like this:
```
X:/Ruby23/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
```
you can fix this error with a little change in **bot/api.rb** file in line **105**
```
      def conn
        @conn ||= Faraday.new(url: 'https://api.telegram.org', :ssl => {:ca_file => "#{Dir.pwd}/cacert_file_name_in_script_folder.pem"}) 
        ...
```
@atipugin think about this ...

**Comment by ivanovaleksey** [comment]
Maybe think about using windows ☺️

**Comment by chinweokwu** [comment]
C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/net/http.rb:934:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (Faraday::SSLError)

**Comment by chinweokwu** [comment]
i have same issue while trying. i checked my network and my network is strong. i need help pls

**Comment by aleksandr-saratovcev** [comment]
> C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/net/http.rb:934:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (Faraday::SSLError)

Did you read this [issue](https://github.com/lostisland/faraday/issues/392)?
