### ISSUE TITLE
Downloading a file

### ISSUE THREAD

**Issue by api-walker** [atipugin/telegram-bot-ruby#104]
Is it possible to download a file after using the get_file method?

**Comment by ivanovaleksey** [comment]
Have you read the method [documentation](https://core.telegram.org/bots/api#getfile)?

**Comment by api-walker** [comment]
Yes, after executing bot.api.get_file(file_id: message.document.file_id) I get a hash with the needed attributes. But which method executes a GET to https://api.telegram.org/file/bot<token>/<file_path>?

**Comment by ivanovaleksey** [comment]
I believe there is no such method in the gem since there is no such method in Telegram API itself (and the gem only forwards all methods).
You should just create a link (as it's described in the docs) and send `GET` request manually.

**Comment by api-walker** [comment]
Wouldn't it be nice if the gem allows this operation? It knows the bot token and uses already Faraday.

**Comment by ivanovaleksey** [comment]
To be honest I don't work with files so it's not necessary feature for me.
You can discuss it with @atipugin.
It does not fit well with current nice implementation (which I think is really good enough). Telegram API also doesn't provide a separate method for downloading a file.

**Comment by api-walker** [comment]
OK, thank you.
