### ISSUE TITLE
request_contact TELEGRAM delivery

### ISSUE THREAD

**Issue by akushneruk** [atipugin/telegram-bot-ruby#105]
Got a problem with the delivery of the message to the phone user, although other messages are good. Using saved 100% working version - the same problems.

`Telegram::Bot::Types::KeyboardButton.new(text: 'Allow me see your phone', request_contact: true)`

Tried some time - works

[img](https://i.stack.imgur.com/fZ01h.png)

**Comment by ivanovaleksey** [comment]
I can't not reproduce a bug.
My code is 
```
button = Telegram::Bot::Types::KeyboardButton.new(text: 'Allow me see your phone', request_contact: true)
markup = Telegram::Bot::Types::ReplyKeyboardMarkup.new(keyboard: [[button]])
bot.api.send_message(
  chat_id: message.from.id,
  reply_markup: markup
)
```
Everything works fine.
![image](https://cloud.githubusercontent.com/assets/11523473/22816744/c7bff6e4-ef74-11e6-8794-6e203030f708.png)

**Comment by akushneruk** [comment]
From web:



![screenshot from 2017-02-10 12-08-37](https://cloud.githubusercontent.com/assets/7112520/22822959/4c88a992-ef8a-11e6-9c15-724480d6bd84.png)

**Comment by akushneruk** [comment]
But I did not quickly sending messages. Research methods in 24 hours I again can send messages

**Comment by akushneruk** [comment]
well, it will issue # 2, the question is how, after inquiries phone lock custom button??

**Comment by ivanovaleksey** [comment]
You can't lock keyboard button. You can hide with `one_time_keyboard` parameter is set to `true`.
See [docs](https://core.telegram.org/bots/api#replykeyboardmarkup).
Also you can send message with special keyboard [ReplyKeyboardRemove](https://core.telegram.org/bots/api#replykeyboardremove) type.

The issue # 2 (as you name it) is not related to the gem I believe.

**Comment by akushneruk** [comment]
So I understand. Thank you very much
