### ISSUE TITLE
Best way to stop thread with bot.listen

### ISSUE THREAD

**Issue by govorov** [atipugin/telegram-bot-ruby#109]
Hi!
I'm creating rails wrapper for `telegram-bot-ruby`.
I've created a railtie that does some configuration magic and then runs bot client in separate thread for each telegram bot.
What's the proper way to stop thread with `bot.listen` in order to shut down properly?

Current implementation is:
```
    def start_client
      client  = @client
      emitter = @emitter

      @thread = Thread.new do
        client.run do |bot|
          bot.listen do |message|
            @emitter.emit :message_received, message
          end
        end
      end
      @thread.abort_on_exception = true
      at_exit { Thread.kill @thread }
    end
```

Thank you!

**Comment by ivanovaleksey** [comment]
It seems like using separate processes for each bot would be more suitable approach because you would have multiple pids to manage them separately.
As far as I know you have to have Thread object itself to manage it.
So you need to store created threads somewhere. But it looks tricky.

**Comment by govorov** [comment]
Using separate thread is only the first step and it is pretty easy for prototyping. I'm going to move listeners to separate processes next and  make them communicate with main rails application via something like rabbit.

**Comment by ivanovaleksey** [comment]
@govorov that makes sense. I think it would be better to start with this approach right now.

**Comment by govorov** [comment]
Anyway, even in a separate process, how should I implement listener shut down properly?
Thank you.

**Comment by ivanovaleksey** [comment]
If you use `Client#listen` bot would only [receive](https://github.com/atipugin/telegram-bot-ruby/blob/master/lib/telegram/bot/client.rb#L24) `INT` signal.
Seems like this way bot would be shut down most gracefully.
You can store process pid on startup and then send signal to the pid.

Is it what you are looking for?

**Comment by govorov** [comment]
Yes, that's exactly what I need.
Thank you!
