### ISSUE TITLE
To permit send raw  Telegram JSON

### ISSUE THREAD

**Issue by luizcarvalho** [atipugin/telegram-bot-ruby#110]
It's possible send raw JSON otherwise use `Telegram::Bot::Types`?

Same like this in [call function](https://github.com/atipugin/telegram-bot-ruby/blob/master/lib/telegram/bot/api.rb#L63): 

```
      def call(endpoint, raw_params = {})
        params = build_params(raw_params)
        directly_call(endpoint, params)
      end

      def directly_call(endpoint, raw_json)
        response = conn.post("/bot#{token}/#{endpoint}", raw_json)
        if response.status == 200
          JSON.parse(response.body)
        else
          raise Exceptions::ResponseError.new(response),
                'Telegram API has returned the error.'
        end
      end
```

And use like this:

`telegram_client.api.directly_call('sendMessage', {:chat_id=>51112220, :text=>"Select options:", :reply_markup=>"{\"keyboard\":[[\"SOLAR\",\"Athenas\",\"SISREF\"]],\"resize_keyboard\":true,\"one_time_keyboard\":true,\"selective\":false}"})`

**Comment by ivanovaleksey** [comment]
The whole idea of the gem is to wrap raw JSON with nice Ruby classes and syntax.
But this is Ruby - you can always do what you want ☺️
