### ISSUE TITLE
Deleting messages

### ISSUE THREAD

**Issue by mafia-007** [atipugin/telegram-bot-ruby#111]
Telegram Bot API - Deleting messages: https://core.telegram.org/bots/api#deleteMessage

**Comment by ivanovaleksey** [comment]
What do you mean by that?
The link is broken.

**Comment by mafia-007** [comment]
Added method Deleting messages 
Is testing telegram

**Comment by ivanovaleksey** [comment]
Sorry I can't understand you.

**Comment by LuisGi93** [comment]
The method for deleting messages: [deleteMessage](https://core.telegram.org/bots/api#deletemessage) is not implement it throws an : 
```
api.rb:53:in `method_missing': undefined method `delete_message' 
```
when used example:
```
        @@bot.api.delete_message( chat_id: @id_chat, message_id: @id_mensaje)
```

**Comment by ivanovaleksey** [comment]
Now I see, thank you for the report. 
I will take a look in a few hours.

**Comment by ivanovaleksey** [comment]
As I can see `deleteMessage` method was added in Bot API 3.0 ([CHANGELOG](https://core.telegram.org/bots/api-changelog#may-18-2017)), right?
We plan to implement API 3.0 changes in #118

**Comment by ivanovaleksey** [comment]
@mafia-007 @LuisGi93 Bot API 3.0 changes was implemented. Please check once again.

**Comment by LuisGi93** [comment]
Working fine, for me this issue is resolved.

**Comment by lecabel** [comment]
Hello, is it possible to clear the history of the chat ? if so how ? I tried like 
`          bot.api.deleteMessage(chat_id: message.chat.id, message_id: message.from.id)
`
but does not work. Thanks

**Comment by ivanovaleksey** [comment]
@lecabel the gem is just a simple wrapper over Bot API. 
Please read [the documentation](https://core.telegram.org/bots/api#deletemessage) thoroughly.
