### ISSUE TITLE
Very slowly request to api.telegram.org

### ISSUE THREAD

**Issue by no-cat-no** [atipugin/telegram-bot-ruby#112]
It's my first bot. Working with webhooks. I send any message and see in NewRelic this

![2017-05-12 8 39 45](https://cloud.githubusercontent.com/assets/25129765/25983984/a1ce9a4e-36f0-11e7-85e7-00ae3733a5da.png)
![2017-05-12 8 40 21](https://cloud.githubusercontent.com/assets/25129765/25983985/a1ceefa8-36f0-11e7-97c9-1fd7ff9d8da3.png)

What's going on here? Why so slow? 3 seconds! 3 seconds - it's fast, because usually 4-6sec for 
one request and response to messenger.

ping to api.telegram.org and google:

```
PING api.telegram.org (149.154.167.200) 56(84) bytes of data.
64 bytes from 149.154.167.200: icmp_req=1 ttl=57 time=35.0 ms
64 bytes from 149.154.167.200: icmp_req=2 ttl=57 time=32.8 ms
64 bytes from 149.154.167.200: icmp_req=3 ttl=57 time=32.5 ms
^C64 bytes from 149.154.167.200: icmp_req=4 ttl=57 time=34.0 ms

--- api.telegram.org ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 15144ms
rtt min/avg/max/mdev = 32.522/33.631/35.080/1.020 ms


PING google.com (216.58.209.142) 56(84) bytes of data.
64 bytes from arn09s05-in-f142.1e100.net (216.58.209.142): icmp_req=1 ttl=56 time=10.8 ms
64 bytes from arn09s05-in-f142.1e100.net (216.58.209.142): icmp_req=2 ttl=56 time=11.2 ms
64 bytes from arn09s05-in-f142.1e100.net (216.58.209.142): icmp_req=3 ttl=56 time=9.60 ms
64 bytes from arn09s05-in-f142.1e100.net (216.58.209.142): icmp_req=4 ttl=56 time=9.60 ms
^C
--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 10284ms
rtt min/avg/max/mdev = 113.657/114.515/116.182/1.241 ms
```

**Comment by ivanovaleksey** [comment]
Whatever the problem is (jf there is any) the gem is just Ruby wrapper. It just provides convinient classes to avoid dealing with raw JSON. 
That is it. The gem does nothing special with networking. 

P.S.
I don't quite undestand what your `ping` command output should give us?
Ping is not equivalent of actual `sendMessage` request.

**Comment by no-cat-no** [comment]
@ivanovaleksey I agree. I will look further. Although I do not know where, I tried a lot ...
