### ISSUE TITLE
Run bot on server

### ISSUE THREAD

**Issue by mm580486** [atipugin/telegram-bot-ruby#116]
Hi guys
How run bot on debian server ?
I write on cli ruby bot.rb but after exit on server bot terminated

**Comment by ivanovaleksey** [comment]
Hi @mm580486, 

if you want want to get help, please provide some additional context.

Show your code and exact commands you are executing.

**Comment by Xasin** [comment]
If you just want to keep the Bot running, you can use `screen`
In a Startup-Script, use `screen -dmS [Screen name] [startup script]`
It will start a screen session that will run in the background, and to which you can attach using `screen -r [Screen name]`

**Comment by GanjMonk** [comment]
Hi @mm580486, you can try to use Upstart, following links should help
http://blog.arkency.com/2014/06/create-run-and-manage-your-background-processes-with-upstart/
https://askubuntu.com/questions/660523/run-a-ruby-program-on-startup
