### ISSUE TITLE
"403", description: "Bot was blocked by the user"

### ISSUE THREAD

**Issue by angelacode** [atipugin/telegram-bot-ruby#117]
My dev environment works fine, but for a different token running in heroku, I get the following error:

> #1351 Telegram::Bot::Exceptions::ResponseError: Telegram API has returned the error. (ok: "false", error_code: "403", description: "Bot was blocked by the user") 

I'm not clear what else I can do, that's all I have and the implementation is the same on the working bot.

**Comment by cippaciong** [comment]
See #58 
In the end I switched to webhooks so I'm not having this problem anymore

**Comment by angelacode** [comment]
Is that something I do in the config?

**Comment by rauanfelipe** [comment]
you can try:

`
     def process
        begin
          send_message(text: @message)
        rescue Telegram::Bot::Exceptions::ResponseError
          return
        end
      end
`
