### ISSUE TITLE
How  resend a photo that is already on the Telegram servers?

### ISSUE THREAD

**Issue by SergeyAlekseevN** [atipugin/telegram-bot-ruby#12]
The official docs  in https://core.telegram.org/bots/api#sendphoto says:
>Photo to send. You can either pass a file_id as String to resend a photo that is already on the Telegram servers, or upload a new photo using multipart/form-data.
>

In this regard, I have a question: how to make by telegram-bot-Ruby.
I have not found a solution in the source code.

Maybe I missed something, I have only recently started to learn Ruby.
Waiting for your reply.

**Comment by SergeyAlekseevN** [comment]
Thank you, I've already got it.
This code works:

```
file_id ="AgADAgAD9akxG3Uw2AfXaG0i146Xfv7mWSoABI13qxZCZUXXXXXXXXXX"
bot.api.sendPhoto(chat_id: message.chat.id, photo: file_id)
```

**Comment by atipugin** [comment]
You're welcome :)
