### ISSUE TITLE
receiving a 409 error running similar code with different bot API's 

### ISSUE THREAD

**Issue by angelacode** [atipugin/telegram-bot-ruby#120]
I am running the same code using different APIs (one for the dev bot, one for the production bot) on the same hosted infrastructure on Digital Ocean.  However, the production bot keeps getting this error:

> Telegram::Bot::Exceptions::ResponseError: Telegram API has returned the error. (ok: "false", error_code: "409", description: "Conflict: terminated by other long poll or webhook")

**Comment by ivanovaleksey** [comment]
It is hard to help you somehow.
What does it mean "different APIs"?
Are you sure bots are running with different tokens?

**Comment by angelacode** [comment]
Yes, they are.  That's what I meant by different API's, they have a different token.
