### ISSUE TITLE
working with telegram payments

### ISSUE THREAD

**Issue by angelacode** [atipugin/telegram-bot-ruby#121]
Hi, I enabled my bots to accept payments ,is this something that is supported with this gem?

**Comment by atipugin** [comment]
Not yet, @ivanovaleksey is working on implementing new functionality.

**Comment by angelacode** [comment]
I see, thanks for the update.  Didn't see the new methods implemented.

**Comment by ivanovaleksey** [comment]
@angelacode please see #118 for the updates.
