### ISSUE TITLE
method getChatMember doesn't return what it should

### ISSUE THREAD

**Issue by lukeovalle** [atipugin/telegram-bot-ruby#124]
it's returning the hash
`{"ok"=>true, "result"=>{"user"=>{"id"=>240524686, "first_name"=>"Luke", "last_name"=>"Lucas", "username"=>"lukeovalle", "language_code"=>"es"}, "status"=>"creator"}}
`
i guess it should return a `Telegram::Bot::Types::ChatMember` type

**Comment by ivanovaleksey** [comment]
@lukeovalle I think the issue would be closed via #127
