### ISSUE TITLE
answerCallbackQuery how get parameters

### ISSUE THREAD

**Issue by Qj7** [atipugin/telegram-bot-ruby#126]
how i can get value if user add bot with params

for example

telegram.me/your_bot?start=1
...
`bot.listen do |message|`
  `case message`
`when Telegram::Bot::Types::CallbackQuery`
`  if message.data == '1'`
`    do something`
`  end`
`end`
...
not working

**Comment by ivanovaleksey** [comment]
First of all - always format your code.
Why on Earth do you work with `CallbackQuery`?
All you have is `Message` object, inspect it to see what is contains.

**Comment by Qj7** [comment]
because it says in api documentation [https://core.telegram.org/bots/api#answercallbackquery](url)
also if u talking about use smth like:
`bot.listen do |message|`
  `case message.text`
 ` when '1'`
`do something`
`end`
`end`
for example above

**Comment by ivanovaleksey** [comment]
You can use triple backticks (```) to format multiline code.
You provide documentation for `answerCallbackQuery` but I don't see it your code.
Do you use it?
Please provide read code (not foo-bar examples) if want to get help.
And once again
> All you have is Message object, inspect it to see what is contains.
