### ISSUE TITLE
not working parse_mode

### ISSUE THREAD

**Issue by shayanzare** [atipugin/telegram-bot-ruby#129]
Hello.

why is not working parse_mode api in **telegram-bot-ruby** gem ?

**Comment by ivanovaleksey** [comment]
Hi @shayanzare,

please provide additional details if you want to get help.

**Comment by shayanzare** [comment]
Hi @ivanovaleksey 
I need bold or italic text with parse_mode but is not working and bot has been crashed!

**Comment by ivanovaleksey** [comment]
@shayanzare by "additional details" I mean exact message with formatting and how you send it.

**Comment by virgildantas** [comment]
i have tried this:

**Pasdfasdfasdfasdf** 
sdfasdfasdf

@bold **Pasdfasdfasdfasdf** 
sdfasdfasdf

*Pasdfasdfasdfasdf* 
sdfasdfasdf

<b>Pasdfasdfasdfasdf</b> 
sdfasdfasdf

<b>Pasdfasdfasdfasdf</b> 
sdfasdfasdf

<b>Pasdfasdfasdfasdf</b> 
sdfasdfasdf

@bold *Pasdfasdfasdfasdf* 
sdfasdfasdf

and nothing works, direct on bot

**Comment by virgildantas** [comment]
https://github.com/atipugin/telegram-bot-ruby/issues/99

solved my problem. thanks
