### ISSUE TITLE
It would be nice to be able to stop the bot gracefully

### ISSUE THREAD

**Issue by thibauld** [atipugin/telegram-bot-ruby#13]
I did not find a way to stop the bot gracefully. When you stop the bot today (via CTRL-C or any UNIX standard signal), it just spits an error:
```
^C/usr/lib/ruby/1.9.1/net/protocol.rb:143:in `select': Interrupt
	from /usr/lib/ruby/1.9.1/net/protocol.rb:143:in `rescue in rbuf_fill'
	from /usr/lib/ruby/1.9.1/net/protocol.rb:140:in `rbuf_fill'
	from /usr/lib/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
	from /usr/lib/ruby/1.9.1/net/protocol.rb:132:in `readline'
	from /usr/lib/ruby/1.9.1/net/http.rb:2563:in `read_status_line'
	from /usr/lib/ruby/1.9.1/net/http.rb:2552:in `read_new'
	from /usr/lib/ruby/1.9.1/net/http.rb:1320:in `block in transport_request'
	from /usr/lib/ruby/1.9.1/net/http.rb:1317:in `catch'
	from /usr/lib/ruby/1.9.1/net/http.rb:1317:in `transport_request'
	from /usr/lib/ruby/1.9.1/net/http.rb:1294:in `request'
	from /var/lib/gems/1.9.1/gems/persistent_http-1.0.6/lib/persistent_http.rb:304:in `block in request'
	from /var/lib/gems/1.9.1/gems/gene_pool-1.4.1/lib/gene_pool.rb:137:in `with_connection'
	from /var/lib/gems/1.9.1/gems/persistent_http-1.0.6/lib/persistent_http.rb:299:in `request'
	from /var/lib/gems/1.9.1/gems/httparty-0.13.5/lib/httparty/request.rb:101:in `perform'
	from /var/lib/gems/1.9.1/gems/httparty-0.13.5/lib/httparty.rb:522:in `perform_request'
	from /var/lib/gems/1.9.1/gems/httmultiparty-0.3.16/lib/httmultiparty.rb:124:in `post'
	from /var/lib/gems/1.9.1/gems/telegram-bot-ruby-0.3.2/lib/telegram/bot/api.rb:32:in `call'
	from /var/lib/gems/1.9.1/gems/telegram-bot-ruby-0.3.2/lib/telegram/bot/api.rb:27:in `method_missing'
	from /var/lib/gems/1.9.1/gems/telegram-bot-ruby-0.3.2/lib/telegram/bot/client.rb:27:in `block in listen'
	from /var/lib/gems/1.9.1/gems/telegram-bot-ruby-0.3.2/lib/telegram/bot/client.rb:26:in `loop'
	from /var/lib/gems/1.9.1/gems/telegram-bot-ruby-0.3.2/lib/telegram/bot/client.rb:26:in `listen'
	from bot.rb:34:in `block in run'
	from /var/lib/gems/1.9.1/gems/telegram-bot-ruby-0.3.2/lib/telegram/bot/client.rb:22:in `run'
	from /var/lib/gems/1.9.1/gems/telegram-bot-ruby-0.3.2/lib/telegram/bot/client.rb:10:in `run'
	from bot.rb:33:in `run'
	from bot.rb:43:in `<main>'
```

It would be nice to be able to do something like for webrick (see the following example) so that the bot can be stopped without crashing :
```
require 'webrick'
server = WEBrick::HTTPServer.new :Port => 1234
server.mount "/", WEBrick::HTTPServlet::FileHandler, './'
trap('INT') { server.stop }
server.start
```

**Comment by atipugin** [comment]
Good point, i have been thinking about it too. I'll try implement this feature in near future.

**Comment by atipugin** [comment]
Added graceful shutdown in 0.3.6.

**Comment by crondaemon** [comment]
I'd jump into this ticket, since, with the main provided example and with 0.7.2, the ctrl-c seems not to work. Can you confirm this or it's just me?

**Comment by crondaemon** [comment]
I've read the source code and I've got the problem. The listen loop checks the variable 'running' for every cycle. The point is "should I start the next cycle or not?". But the cycle is not interrupted, then: if I send ctrl-c, the software exits _only_ when the next message arrives. I'll try to patch the code and send a PR to you.

**Comment by ivanovaleksey** [comment]
Are you sure about "only when the next message arrives"?
Yes, `Client#fetch_updates` method is not interrupted, but let's look at this scenario:

1. `Client#fetch_updates` is already started
2. You press Ctrl+C
3. `running` is set to false, `Client#fetch_updates` continues to yield received messages to you. So you process all the messages (which is fine I believe)
4. Next `Client#fetch_updates` call is not going to be happened, no new messages arrive.
5. Exit

Is something wrong here?

**Comment by crondaemon** [comment]
IMHO: yes. If I press ctrl-c, and no message arrives, the client doesn't quit.

**Comment by atipugin** [comment]
It will quit after timeout period.

**Comment by ivanovaleksey** [comment]
Yes, I reproduce it myself. But if you send it INT signal it will quit as it should. I just run `kill -INT BOT_PID` from another terminal window.

**Comment by crondaemon** [comment]
Of course it works. But wouldn't it nicer to stopwith ctrl-c? What's the value of getting the last messages in the queue, if we're quitting anyway? Whouldn't it be better to run exit when the signal is got?

**Comment by crondaemon** [comment]
Is the timeout configurable?

**Comment by crondaemon** [comment]
I succeeded to make the client to quit faster with

```
bot.options[:timeout] = 1
```
