### ISSUE TITLE
Stopped working long polling

### ISSUE THREAD

**Issue by ashaninBenjamin** [atipugin/telegram-bot-ruby#140]
My bot successfully has used long polling for a half year. It has worked well. But recently it conked out.
It seems to work like simple `sleep 60`, bot receives the message and then go to sleep for a minute again.
Bot uses long polling with faraday default `net_http` adapter.
Does anybody know how to solve the issue?

**Comment by Wowu** [comment]
Same issue with webhooks.

**Comment by Wowu** [comment]
In my case it's related to Botan, which is apparently not working.
This is probably why there've just dropped botan.io support in #141

**Comment by ivanovaleksey** [comment]
@ashaninBenjamin if you are using Botan.io in the bot you have problems with, try to disable it temporary and check if problems still exist.

**Comment by ashaninBenjamin** [comment]
Disabling Botan solves the problem. Thank you for help.
