### ISSUE TITLE
How to receive image sent by users?

### ISSUE THREAD

**Issue by tlekbalkai** [atipugin/telegram-bot-ruby#143]
How to receive image sent by users?

**Comment by tlekbalkai** [comment]
Solved:
puts(bot.api.get_updates.dig('result',0,'message','photo',-1,'file_id'))
          file_id = bot.api.get_updates.dig('result',0,'message','photo',-1,'file_id')
          file = bot.api.get_file(file_id: file_id)
          file_path = file.dig('result', 'file_path')
          photo_url = "https://api.telegram.org/file/bot#{token}/#{file_path}"

**Comment by ivanovaleksey** [comment]
@tlekbalkai you can close the issue
