### ISSUE TITLE
Missing attribute for message new_chat_member

### ISSUE THREAD

**Issue by AAraKKe** [atipugin/telegram-bot-ruby#148]
Since some versions ago the Message type has the new_chat_memebers which seems to have be renamed in the gem from the old new_chat_member (singular). This method still exists and is the only way, as far as I know, to check if a message is of the type "New chat memeber has joined the group". Without this one cannot check this, please add it back.

**Comment by ivanovaleksey** [comment]
Hi @AAraKKe, please see #146.
The Telegram team says 
>  Replaced the field new_chat_member in Message with new_chat_members (the old field will still be available for a while for compatibility purposes)

Doesn't `new_chat_members` work for you?

**Comment by xdb6f** [comment]
UP

**Comment by AAraKKe** [comment]
It was some time ago when I posted this issue and I don't remember exactly what I did. The issue is that this field tells you if there are new chat members but it doesn't tell you if Telegram sends an update to the bot related a new hat member joining the group. As soon as I have some time I will revisit this and let you know what the issue was and if I found an answer for this.
