### ISSUE TITLE
Responding inline with an image

### ISSUE THREAD

**Issue by piedoom** [atipugin/telegram-bot-ruby#149]
I'm trying to make a bot that searches images, displays results, and allows a user to click one and send it (like the gif bot).  However, it seems that the InputTextMessageContent only accepts a "message_text" string.  I can make that text the URL of the image in question, and it will upload itself.  However, I'm wondering if there is a way to just respond with an image short of making a new message, downloading the image, and reuploading.

**Comment by ivanovaleksey** [comment]
I don't have experience with all these `InlineQuery*` things.
But it is said in [the documentation](InputTextMessageContent) that using _input_message_content_ is some kind of alternative way.
Why do you need to use _ input_message_content_?

Also there is some cached results, for instance [`InlineQueryResultCachedPhoto`](https://core.telegram.org/bots/api#inlinequeryresultcachedphoto). Maybe it can help to avoid "reuploading".
