### ISSUE TITLE
getBot()

### ISSUE THREAD

**Issue by servdo** [atipugin/telegram-bot-ruby#15]
Привет.
На сколько я смог понять, бот стартует и "слушает" сообщения от пользователей. Таким образом, есть возможность "отвечать" им. Но что, если необходимо просто напрямую написать что-то? Например, отправить новость. Для этого мне нужно получить объект bot и, зная chat_id, отправить сообщение. Так как можно реализовать это используя твой gem?
Спасибо.

**Comment by atipugin** [comment]
Привет!

Да, конечно. Например, так:

```ruby
@bot = Telegram::Bot::Client.new(TELEGRAM_BOT_TOKEN)

# Отправляем сообщение сами
def send_message(chat_id, text)
  @bot.api.send_message(chat_id: chat_id, text: text)
end

# Следим за входящими сообщениями
@bot.listen do |message|
  # ...
end
```

**Comment by servdo** [comment]
Нормально каждый раз для отправки сообщения создавать новые инстансы. Тем более после того, как был сделан **run** бот уже запущен?

**Comment by atipugin** [comment]
Не понял. В примере выше создается один инстанс.

**Comment by servdo** [comment]
Надо на практике попробовать.
Спасибо.
