### ISSUE TITLE
getFile doesn't exist

### ISSUE THREAD

**Issue by andreassteph** [atipugin/telegram-bot-ruby#16]

**Comment by atipugin** [comment]
Yes, it is, because these changes in Telegram's Bot api were made 4 days ago. I'll implement it asap.

**Comment by andreassteph** [comment]
Didn't realize it was that recent. Thank You!
Awesome gem

**Comment by mamal72** [comment]
Just pushed a [PR](https://github.com/atipugin/telegram-bot-ruby/pull/17). I think it'll fix this issue.

**Comment by atipugin** [comment]
I've just released 0.3.8 with File api support. thx @mamal72
