### ISSUE TITLE
Uninitialized constant Telegram::Bot::Types::InputMediaPhoto

### ISSUE THREAD

**Issue by Someone443** [atipugin/telegram-bot-ruby#163]
This error appears when I try to create an instance of InputMediaPhoto type to send inside media group.
Probably InputMediaPhoto and InputMediaVideo types are missed in[ '/lib/telegram/bot/types.rb'](https://github.com/atipugin/telegram-bot-ruby/blob/master/lib/telegram/bot/types.rb) file.

**Comment by ivanovaleksey** [comment]
Thank for the reporting. 
We have not yet implemented Bot API 3.5. 
I will to do it ASAP.

**Comment by Someone443** [comment]
I'm using the latest version - 0.8.6

**Comment by ivanovaleksey** [comment]
@Someone443 you can track #164. It fixes the issue.

**Comment by atipugin** [comment]
Yep, my bad! @ivanovaleksey thanks for pr!
