### ISSUE TITLE
undefined method `first_name' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by bleedr** [atipugin/telegram-bot-ruby#165]
When I run the example script I get the error!

`pp message` shows  `@from=nil` when I run it in a channel, which is broadcast only

$ gem list telegram

*** LOCAL GEMS ***

telegram-bot-ruby (0.8.6.1)

**Comment by ivanovaleksey** [comment]
I believe example is not meant to be working in any situation.
Different fields in a received message can be present/blank in different types of chat.
Try to better inspect `message`. Maybe in your case it would be `message.chat`.
