### ISSUE TITLE
bot.api.send_message does not returns Message?

### ISSUE THREAD

**Issue by zzz-zzz-zz-zz** [atipugin/telegram-bot-ruby#170]
```
Telegram::Bot::Client.run(token, logger: logger) do |bot|
  bot.listen do |message|
    last_message = bot.api.send_message(chat_id: message.chat.id, text: message.text)
    bot.api.edit_message_text(chat_id: message.chat.id,
                              text: "Attempting to edit last message..",
                              message_id: last_message.message_id)
  end
end
```

Code represented above throws 
**undefined method `message_id'** for #<Hash:0x0000000005e09908> **(NoMethodError)**

But telegram API says: _On success, the sent Message is returned_
https://core.telegram.org/bots/api#sendmessage

`puts api.send_message(...)` returns response plain response string in JSON format.

**Comment by ivanovaleksey** [comment]
Thank you for reporting. 
I will take a look today.

**Comment by iaroslav-vak** [comment]
Any news? I'm getting the exact behaviour with https://core.telegram.org/bots/api#sendmessage but the doc states that Message object should be returned.

**Comment by atipugin** [comment]
You can manually create Message from returned hash. Something like this:

```ruby
response = bot.api.send_message(chat_id: message.chat.id, text: message.text)
last_message = Telegram::Bot::Types::Message.new(response)
```

**Comment by iaroslav-vak** [comment]
Handling the result is not a problem, but the incorrect doc - is :)
Maybe it's a convention for responses, which I missed
