### ISSUE TITLE
Bad Request: Message is not modified error if two inline button is clicked at once.

### ISSUE THREAD

**Issue by ghost** [atipugin/telegram-bot-ruby#173]
I have a Telegram bot which utilizes inline keyboard to get user's input. Because it queries a DB, it often takes a while for the next message to come through. 

The first message displays a set of inline options. Once clicked, this message is modified and a second inline keyboard is displayed. However, if users were to click the first inline message buttons rapidly, I get the following error:

`Telegram API has returned the error. (ok: "false", error_code: "400", description: "Bad Request: message is not modified") (Telegram::Bot::Exceptions::ResponseError)`

I suspect this has to do with the fact that by editing the message, the API needs to know the message ID it has to edit - which is invalidated by the second inline query. As such this error is thrown as the API does not know which message to edit.

Is there a way to mitigate this? Maybe by removing the inline keyboard as soon as any button is pressed?

**Comment by Carrein** [comment]
I managed to circumvent this by using `rescue` in the particular method that prints out the message.

**Comment by yerkimbekov** [comment]
@Carrein Hey, could you please show how you used rescue to solve this error ? thx

**Comment by aleksandr-saratovcev** [comment]
Code example:

```
def some_method
# some code here
rescue Telegram::Bot::Exceptions::ResponseError
end
```
