### ISSUE TITLE
send_location

### ISSUE THREAD

**Issue by iansowinski** [atipugin/telegram-bot-ruby#179]
So it seems, that there is no way now to send location to user, shouldn't we implement it?

**Comment by ivanovaleksey** [comment]
@iansowinski API [does include](https://github.com/atipugin/telegram-bot-ruby/blob/master/lib/telegram/bot/api.rb#L7) `sendLocation method.
Doesn't it work for you?

**Comment by iansowinski** [comment]
Oh, I missed this one. It's working, thanks :)
