### ISSUE TITLE
send_media_group returned error:  "Bad Request: media to send are not specified"

### ISSUE THREAD

**Issue by KachanAnton350504** [atipugin/telegram-bot-ruby#184]
I'm using latest version of gem 0.8.6.1. This error when I try to set 2 photos in my channel. I Use this code:
 
<pre>
 Telegram::Bot::Client.run(TOKEN) do |bot|
  media = [Telegram::Bot::Types::InputMediaPhoto.new(media: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMzFLAE9nbpaqjU9CYVUfcuI_m4U83TYsG3_-T1t3s2q1dzTSO0w"),
           Telegram::Bot::Types::InputMediaPhoto.new(media: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMzFLAE9nbpaqjU9CYVUfcuI_m4U83TYsG3_-T1t3s2q1dzTSO0w")]
  bot.api.send_media_group(chat_id: CHAT_ID, media: media )
end
</pre>

And I get this error: 
 <code> telegram-bot-ruby-0.8.6.1/lib/telegram/bot/api.rb:76:in `call': Telegram API has returned the error. (ok: "false", error_code: "400", description: "Bad Request: media to send are not specified") (Telegram::Bot::Exceptions::ResponseError)
        from /Users/antonkachan/.rvm/gems/ruby-2.4.2/gems/telegram-bot-ruby-0.8.6.1/lib/telegram/bot/api.rb:60:in `method_missing'
</code>

**Comment by KachanAnton350504** [comment]
Probably InputMediaPhoto and InputMediaVideo types are missed in '/lib/telegram/bot/api.rb' file, in the INLINE_QUERY_RESULT_TYPES constant. When I added there Telegram::Bot::Types::InputMediaPhoto my code has worked. Resolve this problem please

**Comment by brauliobo** [comment]
OMG this is still happenning, is this gem abandoned @atipugin? do you want help in maintaining?

**Comment by brauliobo** [comment]
@KachanAnton350504 this issue also happens if using `Faraday::UploadIO` and isn't fixed by @krelly's patch

**Comment by brauliobo** [comment]
using multiple you have to use "attach://" as in https://github.com/php-telegram-bot/core/issues/811, then @krelly patch works

**Comment by atipugin** [comment]
> OMG this is still happening, is this gem abandoned @atipugin? do you want help in maintaining?

@brauliobo Gem is maintained as you can see by releases and changelog. PR #215 wasn't merged because it adds `InputMedia*` types to list of `InlineQueryResult*` which is not correct.

Anyway i've added some changes to `master`, following code should work now:

```ruby
bot.api.send_media_group(
  chat_id: message.chat.id,
  media: [
    Telegram::Bot::Types::InputMediaPhoto.new(media: 'attach://file1'),
    Telegram::Bot::Types::InputMediaPhoto.new(media: 'attach://file2')
  ],
  file1: Faraday::UploadIO.new('/path/to/file1.png', 'image/png'),
  file2: Faraday::UploadIO.new('/path/to/file2.png', 'image/png')
)
```

Please check if everything's ok.

**Comment by antondgx** [comment]
Hi! I have trouble making the send_media_group sample code above work.

Cant seem to read file1 and file2. I suspect there is something with the faraday im not doing right. Any faraday boiler code i need to write in front to make it work? I installed the gem what is clueless of how it works.

Please help! Thanks

**Comment by antondgx** [comment]
The below code dont work! Possible to help me?

`   photos = [Telegram::Bot::Types::InputMediaPhoto.new(media: "photo_2021-10-26_15-04-01-2.jpeg"),
                      Telegram::Bot::Types::InputMediaPhoto.new(media: "photo_2021-10-26_15-04-01-2.jpeg")]

    Telegram::Bot::Client.run(@token) do |bot|
       bot.api.send_media_group(chat_id: message.chat.id, media: photos)
    end`

**Comment by dkirilenko** [comment]
@antondgx Found the solution, can you try this one:
```
photos = [
  Telegram::Bot::Types::InputMediaPhoto.new(
    type: 'photo',
    media: 'https://images.unsplash.com/photo-1453728013993-6d66e9c9123a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80',
    caption: 'MyCaption',
    parse_mode: ''
  ),

  Telegram::Bot::Types::InputMediaPhoto.new(
    type: 'photo',
    media: 'https://images.unsplash.com/photo-1453728013993-6d66e9c9123a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80',
    caption: 'MyCaption',
    parse_mode: ''
  )
]

Telegram::Bot::Client.run('token') do |bot|
  bot.api.send_media_group(
    chat_id: 'chat_id',
    media: photos,
    caption: 'MyCaption'
  )
end
```

It works too for me (you can try to open the file or try the code above instead of sending a request as in my case):
```
Telegram::Bot::Client.run('token') do |bot|
  bot.api.send_media_group(
    chat_id: 'chat_id',
    media: [
      Telegram::Bot::Types::InputMediaPhoto.new(media: 'attach://file1', caption: '123', parse_mode: ''),
      Telegram::Bot::Types::InputMediaPhoto.new(media: 'attach://file2', caption: '123', parse_mode: ''),
      Telegram::Bot::Types::InputMediaPhoto.new(media: 'attach://file3', caption: '123', parse_mode: '')
    ],
    file1: Faraday::FilePart.new(StringIO.new(send_request("/api/v1/cameras/1/snapshot", :get)), 'image/jpeg'),
    file2: Faraday::FilePart.new(StringIO.new(send_request("/api/v1/cameras/2/snapshot", :get)), 'image/jpeg'),
    file3: Faraday::FilePart.new(StringIO.new(send_request("/api/v1/cameras/3/snapshot", :get)), 'image/jpeg'),
    caption: 'My capture'
  )
end
```

Actually had a problem, just added `caption: '123', parse_mode: ''` to the `Telegram::Bot::Types::InputMediaPhoto` and it started work
