### ISSUE TITLE
sendPhoto using upload function doesn't work

### ISSUE THREAD

**Issue by danielchengml** [atipugin/telegram-bot-ruby#185]
Hey guys, I need a bit of help here. Have been stuck for a few days on the sendPhoto function. So I am trying to send a photo from my local disk via telegram bot but can't seem to make it happen.

Here is my code snippet when I try to send a photo locally (from my disk):
`bot.api.send_photo(chat_id: chat.id, photo: open('./lib/services/output/test_image.png'))`

The error returned is:
`Telegram API has returned the error. (ok: "false", error_code: "400", description: "Bad Request: wrong remote file id specified: Wrong character in the string") (Telegram::Bot::Exceptions::ResponseError)`

 If i use a URL, the `send_photo` function works fine:
`bot.api.send_photo(chat_id: chat.id, photo: 'https://example.com/image.png'`

I'm not sure if this is the issue but I amd guessing it's because the file is not posted in `multipart/form-data`. I understand from Telegram's API that for a direct upload function, the file has to be posted as [multipart/form-data](https://core.telegram.org/bots/api#inputfile). 

My question would be whether this ruby-wrapper supports multipart/form-data upload for telegram? If not, is there another way to post the image via the same telegram bot?

Thanks in advance!

**Comment by atipugin** [comment]
Use `Faraday::UploadIO.new` ([example](https://github.com/atipugin/telegram-bot-ruby#file-upload))

**Comment by danielchengml** [comment]
Thanks a lot! Didn't see you example properly.
