### ISSUE TITLE
Message searching?

### ISSUE THREAD

**Issue by Demonstrandum** [atipugin/telegram-bot-ruby#186]
Has this (https://core.telegram.org/method/messages.search) been implemented yet?
How can I use this method in Ruby?

**Comment by atipugin** [comment]
It's not a bot api method

**Comment by Demonstrandum** [comment]
Never mind that then, is it at all possible to do something similar through a bot?

**Comment by Demonstrandum** [comment]
It works now, with some nice places listed on http://www.cuug.ab.ca/dewara/mandelbrot/Mandelbrowser.html
Take the top two for example,


we can generate:
![close_1](https://user-images.githubusercontent.com/26842759/42823116-a7edc926-89d4-11e8-9000-52b463148a62.png)
made with
```
fractal mandelbrot --offset=-0.7463,0.1102 --scale=0.005 --def=1000 -o=close_1.png
```

and

![close_2](https://user-images.githubusercontent.com/26842759/42823162-c69f8ecc-89d4-11e8-8c96-41e07ea9c067.png)
made with
```
fractal mandelbrot --offset=-0.7453,0.1127 --scale=6.5e-4 --def=1000 -o=close_2.png
```


---

Remeber, the deeper you go, the more you should increase your definition (`--def=1500` for example)
