### ISSUE TITLE
User location 

### ISSUE THREAD

**Issue by Bdabrowsky** [atipugin/telegram-bot-ruby#187]
I have a problem. Where I must add message.location.latitude command to get the user's location after getting message with location. Can you add simple example of getting user's latitude and longitude from message. I need this two parameters to build weather bot. Thanks for advice. :) 👍

**Comment by iansowinski** [comment]
You mean getting it as some kind of button inputs or just user sending you location?

**Comment by Bdabrowsky** [comment]
User sends me location bu a button and i have to get this location in numerical variables, not a map on chat.

**Comment by iansowinski** [comment]
Is it still a problem? Ready to help but was on holidays :)

**Comment by Bdabrowsky** [comment]
Yeah, I have same problem for a month. I couldn't solve it. Tried everything. That's link to my code on stackoverflow: https://stackoverflow.com/questions/52017058/cant-get-longitude-and-latitude-in-telegram-bot-ruby 
I think i may be a API bug. Thanks for help

**Comment by Bdabrowsky** [comment]
I don't know what to do.

**Comment by iansowinski** [comment]
Have the answer from SO worked?

**Comment by Bdabrowsky** [comment]
Yup, everything Is working fine. 
Thanks for advice 👍
