### ISSUE TITLE
Make "https://api.telegram.org" URL configurable

### ISSUE THREAD

**Issue by shlima** [atipugin/telegram-bot-ruby#193]
Please make "https://api.telegram.org" URL configurable here https://github.com/atipugin/telegram-bot-ruby/blob/master/lib/telegram/bot/api.rb#L112

**Comment by shlima** [comment]
I have temporarily fixed this issue with the following code:

```ruby
@cli ||= Telegram::Bot::Client.new(token, logger: logger).tap do |c|
  c.api.send(:conn).url_prefix = 'https://proxy.example.com'
end
```

**Comment by markfrst** [comment]
@shlima solved https://github.com/atipugin/telegram-bot-ruby/pull/201

**Comment by markfrst** [comment]
@shlima done https://github.com/atipugin/telegram-bot-ruby/pull/201

**Comment by markfrst** [comment]
@atipugin close please it
