### ISSUE TITLE
Expose error codes in exceptions (502 Bad Gateway)

### ISSUE THREAD

**Issue by oslerw** [atipugin/telegram-bot-ruby#20]
Right now there doesn't appear to be a good way to tell specifically what error code Telegram returns in the case of an error, other than looking at the string coming from `Telegram::Bot::Exceptions::ResponseError`. This approach seems kind of fragile. It would be nice it exposed the numeric code.

My use case for this is that once in a while the Telegram API returns a 502, which is just some temporary gateway error. I'd like my bot to restart itself in this case, but not if the error is a 4xx as it indicates the bot did something wrong and should stop.

I can submit a pull request that implements this, but I was wondering what the best way of doing this is. I could:

1. Expose the data method that is currently private. This would allow objects to inspect the actual response and take actions based on it. This might have design implications.
2. Expose a new method, error_code that contains only the error code.
3. Raise a specific error type for each known Telegram response (one for 409, one for 502, etc). It'd be a lot of new classes.
4. Code the bot by default to keep trying in case of 502 or even 5xx errors, instead of throwing an exception. This is what the [Golang telegram bindings do](https://github.com/Syfaro/telegram-bot-api/issues/14).

I'm curious to what your thoughts are on this. Like I said, I'm happy to take this and work on it, just want to make sure I'm going in the right direction.

**Comment by atipugin** [comment]
@oslerw to be honest, you can access error code through `response` attribute (which is an instance of [HTTParty::Response](http://www.rubydoc.info/github/jnunemaker/httparty/HTTParty/Response)). But it smells bad (as end user shouldn't care about gem internals) and we definitely need to expose code as attribute. So, second option is a way to go.

**Comment by oslerw** [comment]
Fixed in 3f566b8
