### ISSUE TITLE
Bot throws an exception on message.chat.type when message is a poll

### ISSUE THREAD

**Issue by ferdi2005** [atipugin/telegram-bot-ruby#203]
It should return chat type as usual, but it throws an exception if I use method .chat.type on message when it's a poll. (Workaround: using message.respond_to? :type && message.chat.type == 'private')
`Error performing GetUpdatesFromBotJob (Job ID: 9cf9f15f-928c-45ea-926e-378074cc52b8) from Sidekiq(default) in 343.81ms: NoMethodError (undefined method 'chat' for #<Telegram::Bot::Types::Poll:0x00007fc111dc28d0>):`

**Comment by atipugin** [comment]
Yes, it's expected, because [Poll](https://core.telegram.org/bots/api#poll) object doesn't have such attribute. You need to check `message` type explicitly in your code.

**Comment by ferdi2005** [comment]
Why don’t fix this/simplify adding type poll to poll objects? What’s the class in the code?

**Comment by atipugin** [comment]
Because `Chat` class implements [Chat](https://core.telegram.org/bots/api#chat) object from API spec and it's `type` can be only `private`, `group`, `supergroup` or `channel`.
