### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by phykos** [atipugin/telegram-bot-ruby#207]
I was testing some stuff then I started the bot and nothing was going on, even if I setted up the logger
I also tried to change the token; there it printed an error about the token not being valid, but nothing else

**Comment by SolomonBoloshe116** [comment]
as i understood 
if the telegram client gets error, your bot won't work.
so you have to add exception

**Comment by phykos** [comment]
solved, thanks


> as i understood
> if the telegram client gets error, your bot won't work.
> so you have to add exception

solved btw
