### ISSUE TITLE
Downloading files -- how should I do this?

### ISSUE THREAD

**Issue by phykos** [atipugin/telegram-bot-ruby#213]
I have seen a previous issue (https://github.com/atipugin/telegram-bot-ruby/issues/104) but still I can't understand how I should make a function like that

**Comment by alexandr-shadow** [comment]
As I know Telegram API doesn't have such functionality. Probably you need something like [TDLib](https://telegram.org/blog/tdlib)

**Comment by phykos** [comment]
> As I know Telegram API doesn't have such functionality. Probably you need something like [TDLib](https://telegram.org/blog/tdlib)

Oof, thx anyway man
