### ISSUE TITLE
Remove link preview

### ISSUE THREAD

**Issue by AtomicLemon** [atipugin/telegram-bot-ruby#218]
Hi everyone :)

Is it possible to remove the link previews?
![image](https://user-images.githubusercontent.com/46167928/82723944-96a5fc80-9d26-11ea-8579-6008f914a1d8.png)

This can get quite annoying and can make the message much bigger than it has to be.

**Comment by aleksandr-saratovcev** [comment]
Hello, @AtomicLemon 

You can try to pass `disable_web_page_preview: true` as a parameter to the send_message or edit_message method.

Official documentation: https://core.telegram.org/bots/api#editmessagetext

**Comment by AtomicLemon** [comment]
This worked perfectly! Thank you so much for your fast reply :blush: 

+1
