### ISSUE TITLE
How to forward last received message to another chat?

### ISSUE THREAD

**Issue by Scoopsy** [atipugin/telegram-bot-ruby#219]
I am trying to build a bot that can forward the last received message to another chat. 

Example:;
Me>bot: Hey
bot>2ndchat:Hey

newPerson>bot: what are you?
bot>2ndchat: what are you?

This is what ive got so far but it doesnt work, even if i put a value after message_id: is says it was expecting "="

      bot.api.forward_message(to_chat_id: 2*******1, from_chat_id: message.chat.id, message_id: ?)

am i in the right direction or completely off? thanks in advance!

**Comment by aleksandr-saratovcev** [comment]
Did you try to provide a message_id?

` bot.api.forward_message(to_chat_id: 2*******1, from_chat_id: message.chat.id, message_id: message.id)`
