### ISSUE TITLE
Debugging insane delay sending files

### ISSUE THREAD

**Issue by BernH4** [atipugin/telegram-bot-ruby#222]
Hello i just sent a file with this code:
![image](https://user-images.githubusercontent.com/62931413/93921931-8f612080-fd11-11ea-8fdc-a2ec0bb40add.png)
It took more than 11 minutes too complete. (7 MB .mp3 File)

How can i start debugging this issue? Is Telegram limiting me because i sent too much at one day? It worked fine yesterday.
Of course i do not get any console output and i cant kill (STRG + C) while the file is uploading.

Maybe its also my Internet thats suddenly pretty bad, im not experienced in this.
Can someone point me where to start researching/debbuging this issue right know i cant do more than starr at an empty console. 
Appreciate any help, also "google this and this"

**Comment by ivanovaleksey** [comment]
You can try to upload a file with plain `curl` request. Maybe it would give you any hints.
As for Telegram limitations try to contact official support.
