### ISSUE TITLE
Undefined method "text" for message

### ISSUE THREAD

**Issue by arthurborgesdev** [atipugin/telegram-bot-ruby#234]
I received the following error message today: 

`undefined method `text' for #<Telegram::Bot::Types::ChatMemberUpdated:0x0000563028c53a10> (NoMethodError)`

I stopped the hobby dynos of Heroku a few weeks ago, and when I restarted them today I got this message. 

Maybe the API changed? I don't know... my code is hosted here: https://github.com/arthurborgesdev/gamebot

I can submit further tests if needed.

**Comment by atipugin** [comment]
Hi @arthurborgesdev,

Sounds similar to #226, please check out my comment on that issue - https://github.com/atipugin/telegram-bot-ruby/issues/226#issuecomment-797296565

**Comment by EvanBrightside** [comment]
Thank U @atipugin, it works fine!
