### ISSUE TITLE
Please add some more Snippets

### ISSUE THREAD

**Issue by Mangeshrex** [atipugin/telegram-bot-ruby#237]
Tbh i am a beginner and i am trying to learn ruby and on the way i am developnig a bot. The code you gave helped me alot. But can you please add some more snippets like for muting a user or banning him and purging the messages?

**Comment by ternaryCat** [comment]
Hi, you can find an example in this [repo](https://github.com/ternaryCat/fast_avatar). It's currently unsupported project, I improved archetecture in my private project. if you want we may discuss in chat :^)
