### ISSUE TITLE
Faraday v2 | Faraday::Error: :multipart is not registered on Faraday::Request

### ISSUE THREAD

**Issue by epistrephein** [atipugin/telegram-bot-ruby#242]
Faraday v2 separated all modules into different gems
https://github.com/lostisland/faraday/releases/tag/v2.0.0
so Faraday multipart middleware is not included by default when using the new version, raising the error

```
Faraday::Error: :multipart is not registered on Faraday::Request
```

For now, the workaround is to explicitly specify `'faraday', '~> 1.0'` as a dependency.
Long term solution would be to either pin Faraday to ~> 1.0 or properly include faraday-multipart as a dependency and register it.

**Comment by atipugin** [comment]
@epistrephein thanks, i've totally missed faraday's 2.0 release. I've released `0.17.0` with pinned `~> 1.0` version. In future releases i'll probably update it to v2, but need to do some testing before.

**Comment by epistrephein** [comment]
Thanks for the swiftness @atipugin!
Do you want to keep this issue open as a reference for the future fix, or shall I just close it?

**Comment by atipugin** [comment]
I think we can close this issue for now.
