### ISSUE TITLE
Telegram API has returned the error. (ok: "false", error_code: "400", description: "[Error]: PEER_ID_INVALID")

### ISSUE THREAD

**Issue by sealabcore** [atipugin/telegram-bot-ruby#25]
There seems to be a change in how bots can message users on Telegram we used to be able to pass the chat id.

Now when we do this we get the error message
Telegram API has returned the error. (ok: "false", error_code: "400", description: "[Error]: PEER_ID_INVALID")

Any idea how our bot can now message our users that initiate a conversation with us?

**Comment by sealabcore** [comment]
method in question is
```
client.api.send_message(chat_id: <CHAT_ID>, text: 'Hi')
```

**Comment by atipugin** [comment]
Could you provide your code of your bot?

**Comment by sealabcore** [comment]
This is a confirmed Telegram API bug, unrelated to the ruby gem. I have a dialogue open with them on Telegram support channel on Telegram.

Thanks for following up.
