### ISSUE TITLE
AnswerInlineQuery not work correctly

### ISSUE THREAD

**Issue by Murloc111** [atipugin/telegram-bot-ruby#254]
When i update gem from 0.15 to latest 0.19.2, i have errors on sending AnswerInlineQuery:

(ruby 2.7.3)

` results.push Telegram::Bot::Types::InlineQueryResultCachedMpeg4Gif.new(`
  `  id: row.id,`
  `  mpeg4_file_id: row.name`
`)`
`bot.api.answer_inline_query(inline_query_id: query_id,  results: results, cache_time: 0) if !results.nil?`

I have error:

`Telegram API has returned the error. (ok: "false", error_code: "400", description: "Bad Request: can't parse inline query result: Field "input_message_content" must be of type Object")`

However field "input_message_content" is optional, and not to be send, if i dont set it.

Thanks!

**Comment by mvondoyannick** [comment]
I have the same issue. Need help

thanks

**Comment by mvondoyannick** [comment]
I have the same issue, need your help please
![Capture d’écran du 2023-01-13 19-19-40](https://user-images.githubusercontent.com/2368758/212391677-43dbe47a-2f7f-410b-9e6e-b815c6452161.png)

thanks
