### ISSUE TITLE
Answers ReplyKeyboardMarkup

### ISSUE THREAD

**Issue by raphaelmro** [atipugin/telegram-bot-ruby#26]
How can I get the ReplyKeyboardMarkup answer to interact with the user? 
I've tried something like
``` 
puts answers
```
for the given code
```
option = 'What you wanna do?'
        answers =
            Telegram::Bot::Types::ReplyKeyboardMarkup
                .new(keyboard: [%w(Add Remove), %w(Search)], one_time_keyboard: true)
        bot.api.send_message(chat_id: message.chat.id, text: option, reply_markup: answers)
```
but just returned an object.

Thanks

**Comment by atipugin** [comment]
Following code did the job perfectly:

```ruby
require 'bundler/setup'
require 'telegram/bot'

token = 'secret'

Telegram::Bot::Client.run(token) do |bot|
  bot.listen do |message|
    option = 'What you wanna do?'
    answers = Telegram::Bot::Types::ReplyKeyboardMarkup.new(keyboard: [%w(Add Remove), %w(Search)], one_time_keyboard: true)
    bot.api.send_message(chat_id: message.chat.id, text: option, reply_markup: answers)
  end
end
```

Proof pic:

![screen shot 2015-12-07 at 00 08 27](https://cloud.githubusercontent.com/assets/281812/11615604/d56f93f0-9c76-11e5-9fc2-433ff421038e.png)

Seems like something wrong with your code, not the gem.

**Comment by raphaelmro** [comment]
Yes, it works but i wanna do stg like:
When the user type '/help' the 'menu' is opened.
````
Telegram::Bot::Client.run(token_telegram) do |bot|
  bot.listen do |message|
    case message.text
      when '/help'
        option = 'O que você deseja fazer?'
        answers =
            Telegram::Bot::Types::ReplyKeyboardMarkup
                .new(keyboard: [%w(Adicionar Remover), %w(Procurar)], one_time_keyboard: true)
        bot.api.send_message(chat_id: message.chat.id, text: option, reply_markup: answers)
````
...and depending the users' option, i will do an action. The problem is, how can i get the value i choose?
Example: Type '/help' > (Menu is displayed) > Choose 'Add' >(Bot asks for a string to add)> Users type>Store the string(array, hash or db)

**Comment by raphaelmro** [comment]
Sorry, pressed the wrong button and reopened. lol

**Comment by atipugin** [comment]
I got you. You have to store somehow user's current state and decide what to do depending on this state.  In your example, you need to change user's state to "adding_something" if he/she types "/help" and chooses "Add". All next incoming messages from that user should be processed according his state. So, if user with state "adding_something" types "/help" again, you have treat it as a string, not a command to show the help menu.

I did something similar here: https://github.com/atipugin/telekrug. It uses sinatra + webhooks, but general idea is the same. 

Take a look here: https://github.com/atipugin/telekrug/blob/master/app/workers/process_message.rb. This class (sidekiq worker) handles each incoming message from any user.

**Comment by raphaelmro** [comment]
Yeah, i understood but i' having problem to get the 'Add' string when you press the option, in this case my reply to the question. A simple message.text was not supposed to get it? 
```
  Telegram::Bot::Client.run(token_telegram) do |bot|
    bot.listen do |message|
      case message.text
        when '/help'
          option = 'What you wanna do?'
          answers =
              Telegram::Bot::Types::ReplyKeyboardMarkup
                  .new(keyboard: [%w(Add Remove), %w(Search], one_time_keyboard: true)
          bot.api.send_message(chat_id: message.chat.id, text: option, reply_markup: answers)
          my answer = message.text.. #my problem is here - not getting the 'add' reply
          case my_answer
            when "Add"
             # (do stg here)
            when "Remove"
             # (do stg here)
            when "Search"
             # (do stg here)
          end
```
Sorry if it's a newbie question, i'm learning ruby with this project.

**Comment by atipugin** [comment]
It doesn't work this way. You can't handle answers inside `when '/help'` block, because answer message never gets inside that block (as your statement condition clearly says: "only messages with '/help' text goes here").
