### ISSUE TITLE
ArgumentError if message is not a string

### ISSUE THREAD

**Issue by Evillemonpie** [atipugin/telegram-bot-ruby#262]
Hello, I am new to programming. I have a simple code as in the example from the documentation:
require 'telegram/bot'

```
token = 'YOUR_TELEGRAM_BOT_API_TOKEN'

Telegram::Bot::Client.run(token) do |bot|
  bot.listen do |message|
    case message.text
    when '/start'
      bot.api.send_message(chat_id: message.chat.id, text: "Hello, #{message.from.first_name}")
    when '/stop'
      bot.api.send_message(chat_id: message.chat.id, text: "Bye, #{message.from.first_name}")
    end
  end
end

```
when I send a sticker or photo to chat with bot I get an error **.../virtus/attribute/collection.rb:9:in `initialize': wrong number of arguments (given 0, expected 1..3) (ArgumentError)**

**Comment by denisgorbunov** [comment]
same error

**Comment by atipugin** [comment]
Unfortunately I unable reproduce your error. Code from `example/bot.rb` works just fine for me. Do you most recent version of gem (0.21.1)?
