### ISSUE TITLE
Support for inline requests

### ISSUE THREAD

**Issue by hmage** [atipugin/telegram-bot-ruby#30]
Would be nice to have that.

Details here:
https://core.telegram.org/bots/inline

**Comment by tcoenraad** [comment]
:+1:

**Comment by atipugin** [comment]
Thanks for letting me know, will add it asap

**Comment by atipugin** [comment]
I've just released 0.4.0 with [inline bots](https://github.com/atipugin/telegram-bot-ruby#inline-bots) support. Please check it out.
