### ISSUE TITLE
Message.text is nil even thought the schema says it can not be

### ISSUE THREAD

**Issue by thebravoman** [atipugin/telegram-bot-ruby#303]
When sending a message that is just an attached photo the Message.text is nil

```
Telegram::Bot::Client.run(@token) do |bot|
  bot.listen do |telegram_message|
    case telegram_message
    when Telegram::Bot::Types::Message
      Rails.logger.info "telegram_message.text == nil: #{telegram_message.text == nil}"
    end
  end
end
```

results in

```
2024-02-28T06:58:35.323603+00:00 app[worker_telegram_bot.1]: I, [2024-02-28T06:57:35.707711 #2]  INFO -- : telegram_message.text == nil: true
```

How come the attribute is of type 

```
module Telegram
  module Bot
    module Types
      class Message < Base
...
        attribute? :text, Types::String 
      end
    end
   end
end
```

but the message.text is nil?

**Comment by atipugin** [comment]
Hi @thebravoman,

In dry-struct `attribute?` means [attribute is optional](https://dry-rb.org/gems/dry-struct/1.6/recipes/#tolerance-to-missing-keys).

**Comment by thebravoman** [comment]
Ah, makes sense.

**Comment by AlexWayfer** [comment]
And it's also optional in the official documentation, we have checks for this: https://core.telegram.org/bots/api#message

![image](https://github.com/atipugin/telegram-bot-ruby/assets/6510020/41836faa-27d7-43a7-b3bc-8286c4a616fe)

I think, we can close this issue.
