### ISSUE TITLE
send message with markdown

### ISSUE THREAD

**Issue by KirillTemnov** [atipugin/telegram-bot-ruby#31]
try this code:

```ruby
            bot.api.send_message(chat_id: message.chat.id,
                               text: "~~some sample text~~",
                               parse_mode: 'Markdown')

```

with no affect.

**Comment by cippaciong** [comment]
https://core.telegram.org/bots/api#using-markdown
"The Bot API supports very basic markdown. You can use bold and italic text, as well as inline links in your bots' messages. "

**Comment by KirillTemnov** [comment]
I used unsupported (for markdown) clinent :-/

**Comment by UrabeM** [comment]
You should ve left the symbols for each markdowns bro i really confused well thanks to u i got it done.

**Comment by AlexWayfer** [comment]
Just a note: now you can use `MarkdownV2` value: https://core.telegram.org/bots/api#markdownv2-style
