### ISSUE TITLE
Error on photo sending (400)

### ISSUE THREAD

**Issue by alexandrov-va** [atipugin/telegram-bot-ruby#32]
My bot can't send a photo.
```ruby
#initialization above
image_file = File.new('selection.png')
p "BeforeBot"
Telegram::Bot::Client.run(token) do |bot|
  bot.listen do |message|
    case message.text
    when '/fetch'
      p "BeforeResponse"
      bot.api.send_photo(chat_id: message.chat.id, photo: image_file)
      p "AfterResponse"
    end
  end
end
p "AfterBot"
```
It sticks on "BeforeResponse" stage. Then after 1-2 minutes console says:

*/home/vova/.rvm/gems/ruby-2.2.1/gems/telegram-bot-ruby-0.4.0/lib/telegram/bot/api.rb:49:in `call': Telegram API has returned the error. (ok: "false", error_code: "400", description: "[Error]: Bad Request: Wrong persistent file_id specified: contains wrong characters or have wrong length"(Telegram::Bot::Exceptions::ResponseError)*

**Comment by hmage** [comment]
Same here. Sending photos does not work anymore.

**Comment by markkuit** [comment]
Same here. I'm getting a different error but it happens when sending photo/documents.

```/usr/local/share/gems/gems/persistent_http-1.0.6/lib/persistent_http.rb:335:in `rescue in block in request': too many connection resets (due to end of file reached - EOFError)```

Every gem is up-to-date.

**Comment by zeracode** [comment]
I solved the problem for myself (telegram-bot-ruby 0.4.0) as follows:
```ruby
class Telegram::Bot::Api
  private 
  def jsonify_inline_query_results(value)
    return value unless value.class == Array
    return value unless Array(value).all? { |i| INLINE_QUERY_RESULT_TYPES.include?(i.class) }
    value.map { |i| i.to_h.select { |_, v| v } }.to_json
  end
end
```

**Comment by atipugin** [comment]
@zeracode yeah, issue was exactly here, thanks. I've released 0.4.1 with fix.

**Comment by AbdullahAs** [comment]
Same issue here, I have v0.5.2

**Comment by atipugin** [comment]
Please show your code.

**Comment by AbdullahAs** [comment]
Alright after looking for other closed issue it appears that we have to use now the Faraday::UploadIO.new instead of File.new which caused the problem a code that was running fine before. 
maybe it would be a good idea if this change was highlighted with few details in the changelog. thanks.

**Comment by atipugin** [comment]
It is highlighted in README.
