### ISSUE TITLE
Get Chat Id/title

### ISSUE THREAD

**Issue by n4m3less** [atipugin/telegram-bot-ruby#35]
Hi guys, i am new in ruby and i was trying to get the chat id or chat title of the group where the message is send... 

Is it possible? 

i tried message.chat.id and some stuff but didnt work

thanks

**Comment by golodenko** [comment]
For debugging I used comand /chatinfo

`   token =  "TOKEN HERE"
    Telegram::Bot::Client.run(token) do |bot|
      bot.listen do |message|
        case message.text
          when '/start'
            bot.api.sendMessage(chat_id: message.chat.id, text: "Hey, #{message.from.first_name}")
          when '/chatinfo'
            bot.api.sendMessage(chat_id: message.chat.id, text: "Id is: #{message.chat.id}")
            bot.api.sendMessage(chat_id: message.chat.id, text: "More info on message: #{message.to_yaml}")
         end
      end
    end`

Result looks like this:
<img width="957" alt="screen shot 2016-01-28 at 15 46 10" src="https://cloud.githubusercontent.com/assets/1838329/12646000/4cdde01c-c5d6-11e5-8c25-6dca5ad62fc0.png">

Works as charm for group chats as well

**Comment by n4m3less** [comment]
thanks, gonna try and see if it works

**Comment by fredkard** [comment]
I created a bot to get User or GroupChat id, just send the /my_id to telegram bot @get_id. then the bot will reply with your User Chat ID or GroupChat ID.

It does not only work for user chat ID, but also for group chat ID.

To get group chat ID, first you have to add the bot to the group, then send /my_id in the group.

Here's the link to the bot. https://telegram.me/get_id_bot

Sorry if it considered out of topic.

**Comment by Helias** [comment]
@get_id_bot doesn't work (I just tested it)
Use [@GiveChatId_Bot](http://t.me/GiveChatId_Bot) with the command /chatid
