### ISSUE TITLE
Does reply_to_message parameter work?

### ISSUE THREAD

**Issue by sergeyvdovareize** [atipugin/telegram-bot-ruby#38]
Does **reply_to_message** parameter work? Doesn't for me. Do you have any example?
Thanks

**Comment by atipugin** [comment]
Did you mean **reply_to_message_id**? Yes, it does. Could you show your code?

**Comment by sergeyvdovareize** [comment]
@atipugin I can't understand what is **reply_to_message_id**
I see only **reply_to_message** here https://core.telegram.org/bots/api#message

1 Here is my code:
```ruby
msg = 'set new status'
statuses =
    Telegram::Bot::Types::ReplyKeyboardMarkup
        .new(keyboard: [%w(Yes No)], one_time_keyboard: true, resize_keyboard: true)

bot.api.send_message(chat_id: message.chat.id, text: msg, reply_markup: statuses, reply_to_message: message)
```

2 Here is the message in telegram:
![telegam]
(http://i.imgur.com/S1ahNlQ.png) 

3 And here is a part of a replay message.  **reply_to_message** is empty
![replay]
(http://i.imgur.com/fMQc6Vu.png)

What am I doing wrong?

**Comment by atipugin** [comment]
You have to take a look at [sendMessage](https://core.telegram.org/bots/api#sendmessage) method. 

Use following code:
```ruby
bot.api.send_message(chat_id: message.chat.id, text: msg, reply_markup: statuses, reply_to_message_id: message.id)
```
