### ISSUE TITLE
The unhandled exception with supergroups

### ISSUE THREAD

**Issue by Spalf** [atipugin/telegram-bot-ruby#40]
After update group to supergroup with bot:
`ruby/2.2.0/gems/telegram-bot-ruby-0.4.2/lib/telegram/bot/api.rb:56:in`call': Telegram API has returned the error. (ok: "false", error_code: "400", description: "[Error]: Bad Request: group chat is migrated to supergroup chat", parameters: "{"migrate_to_chat_id"=>-*****************}") (Telegram::Bot::Exceptions::ResponseError)`

**Comment by arn01d** [comment]
I am having the same issue. Correct me if I am wrong, but the way I understand it, is that this error occurs only if a group is upgraded to a supergroup while the bot is a member of the group. _(If a bot is added to an existing supergroup this does not occur)_

When a group is migrated to a supergroup, it gets a new `chat_id` that is passed to the bot in the group in the field  `migrate_to_chat_id`. This is now the `chat_id` that the bot should use to send messages in the group. By using the old one, we get that kind of error. 

@atipugin will you be adding the ability to handle the _upgraded to supergroup_ service message to the gem?

**Comment by atipugin** [comment]
I'm not sure how to handle it. Resend message with new chat_id? What if you store your chat ids somewhere in db? In this case you need to handle it by your own.
