### ISSUE TITLE
Support Telegram Bot API v2.0

### ISSUE THREAD

**Issue by macteo** [atipugin/telegram-bot-ruby#41]
Today Telegram introduced many interesting features like:

- Inline Keyboards.
- Callback buttons.
- Switch to inline buttons.
- Updating messages.
- Location and telephone access.
- Inline bots 2.0 (with support for 19 content types).

https://core.telegram.org/bots/2-0-intro

Here there is the [complete changelog](https://core.telegram.org/bots/api#recent-changes).

Keep up the amazing work, thanks.

**Comment by atipugin** [comment]
Hi and thanks for letting me know about api updates. Will implement these features in a couple of days.

**Comment by macteo** [comment]
Thanks you rock!

**Comment by araishikeiwai** [comment]
will be waiting for `entities` and inline keyboards/message edit :relaxed:

**Comment by josephmbeveridge** [comment]
Thank you for being so quick 😊

**Comment by atipugin** [comment]
I've just released `0.5.0.beta2`,update your gemfiles with following:

```ruby
gem 'telegram-bot-ruby', '~> 0.5.0.beta2'
```

Please give it a try and let me know if any errors occur.
