### ISSUE TITLE
problem with InlineQueryResultArticle

### ISSUE THREAD

**Issue by Ethreal** [atipugin/telegram-bot-ruby#42]
Got an error while trying to use inline queries, particularly InlineQueryResultArticle from readme
`/Library/Ruby/Gems/2.0.0/gems/telegram-bot-ruby-0.4.2/lib/telegram/bot/api.rb:80:in `block in jsonify_inline_query_results': undefined method `to_h' for #<Telegram::Bot::Types::InlineQueryResultArticle:0x007fd8ebb90db8> (NoMethodError)`

**Comment by atipugin** [comment]
Please show your code.

**Comment by Ethreal** [comment]
Telegram::Bot::Client.run(token) do |bot|
      bot.listen do |message|

        case message
        when Telegram::Bot::Types::InlineQuery
          puts " InlineQuery @#{message.from.username}: #{message.query}"
          results = [
            Telegram::Bot::Types::InlineQueryResultArticle
              .new(id: 1, title: 'First article', message_text: 'Very interesting text goes here.'),
            Telegram::Bot::Types::InlineQueryResultArticle
              .new(id: 2, title: 'Second article', message_text: 'Another interesting text here.')
          ]
          bot.api.answer_inline_query(inline_query_id: message.id, results: results)
        when Telegram::Bot::Types::Message
          puts "Message @#{message.from.username}: #{message.text}"
          bot.api.send_message(chat_id: message.chat.id, text: "Hello, #{message.from.first_name}!")
        end
      end
      end

**Comment by atipugin** [comment]
The code you've posted works for me:

![screen shot 2016-04-13 at 15 29 46](https://cloud.githubusercontent.com/assets/281812/14493184/b6b9f93e-018c-11e6-8b4c-72aae6e4fa68.png)

I'm sure you made a mistake somewhere ;)

**Comment by Ethreal** [comment]
Sorry for bothering you. Well, I tried 10 different ways and Telegram API even answers me `{"ok"=>true, "result"=>true}` but still nothing shows up in the chat. Could you kindly give me a working example? %)

Here's my attempt:
Telegram::Bot::Client.run(token) do |bot|
  bot.listen do |message|

    case message
    when Telegram::Bot::Types::InlineQuery
      puts " InlineQuery @#{message.from.username}: #{message.query} and #{message.id}"

      contents = JSON.parse('{"type":"photo","photo_url":"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTsPVdRJ4uDLjvYtnXlk-WxXA_7GGVSgWqU7JArkafRqju2zO-fcA","thumb_url":"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTsPVdRJ4uDLjvYtnXlk-WxXA_7GGVSgWqU7JArkafRqju2zO-fcA"}')
      puts bot.api.answer_inline_query(inline_query_id: message.id, results: contents)
    end
  end
end

**Comment by Ethreal** [comment]
Well, it works now! Well done! :tada:
