### ISSUE TITLE
Telegram::Bot::Types::InlineKeyboardButton not implemented in v0.4.2

### ISSUE THREAD

**Issue by leocabeza** [atipugin/telegram-bot-ruby#46]
It shows this error: 

> uninitialized constant Telegram::Bot::Types::InlineKeyboardButton (NameError)

My fix was to use the beta version, just in case anyone has the same error.

`gem 'telegram-bot-ruby', '~> 0.5.0.beta2'`

**Comment by atipugin** [comment]
Thx, updated readme.
