### ISSUE TITLE
Cannot send files anymore (version 0.5.0)

### ISSUE THREAD

**Issue by macteo** [atipugin/telegram-bot-ruby#50]
Hello,
after the 0.5.0 release I'm not able to send files anymore.

    bot.api.send_voice(chat_id: message.chat.id, voice: File.new(path), caption: caption)

I'm getting error 400 from telegram's API, telling that the `file_id` is too long or contains not allowed chars (I don't specify a `file_id`).

Downgrading to version 0.4.2 fixes the issue.

**Comment by atipugin** [comment]
Hi!

Use `Faraday::UploadIO.new` instead of `File.new` (see example here: https://github.com/atipugin/telegram-bot-ruby#file-upload)

**Comment by macteo** [comment]
👍 thanks!
