### ISSUE TITLE
File Upload not working 

### ISSUE THREAD

**Issue by arn01d** [atipugin/telegram-bot-ruby#51]
The file upload code is not working and causing bots to hang.  The following code in my bots on OpenShift & Heroku was working until about 3 days ago. There are no error messages being thrown to log files

`bot.api.send_photo(chat_id: message.from.id, photo: Faraday::UploadIO.new('creative.png', 'image/jpeg'))`

Has something changed?

**Comment by mm580486** [comment]
hi @arnoldmarunda i have some issue like this , can you solve this problem ?
https://github.com/atipugin/telegram-bot-ruby/issues/153
