### ISSUE TITLE
markdown square bracket characters [ ] dont work

### ISSUE THREAD

**Issue by lsaavedr** [atipugin/telegram-bot-ruby#52]
dont work:

`bot.api.sendMessage(chat_id: message.chat.id, text: "\[dont show in brackets\]", parse_mode: "Markdown")`

work, but why?:

`bot.api.sendMessage(chat_id: message.chat.id, text: "\\[show in brackets\]", parse_mode: "Markdown")`

regards,
Luis

**Comment by atipugin** [comment]
I believe it's Telegram API's issue, as gem doesn't do any markdown transformation and sends your data as is.

**Comment by lsaavedr** [comment]
HowTo see the RESTful request ?

**Comment by lsaavedr** [comment]
maybe it is a faraday hash-parse-params-to-generate-request-url problem...

**Comment by lsaavedr** [comment]
was because text must be surrounded with ' not with " (ruby style), but the second scape '\\]' it's not necessary and it's an API's issue?
