### ISSUE TITLE
How do i use the edit_message_text method

### ISSUE THREAD

**Issue by arn01d** [atipugin/telegram-bot-ruby#54]
I believe the correct syntax should be as follows;

bot.api.edit_message_text(chat_id: **message.from.id**, message_id: **message.message_id**, text: 'Hello Ruby', reply_markup: kbmarkup)

What should the **message_id:** be? Because I get the following error;

_undefined method `message_id' for # Telegram::Bot::Types::CallbackQuery:0x007f867a1efae8 (NoMethodError)_

**Comment by arn01d** [comment]
The Bot API documentation implies the **message_id** should be  **message.message_id** or possibly **message.id.** I have tried these both with no success. 

Therefore, I and others now believe that there is an issue/bug with the **send_message_text** method in this gem implementation.  

> I consider myself a layman and may be missing something that is causing the error, and would greatly appreciate your response Alexander, as I value your work, and how it has contributed to my projects.

**Comment by atipugin** [comment]
Hi @arn01d! `message` object may vary depending on user interaction. You need to check it's type and handle each possible case on your own, [see an example](https://github.com/atipugin/telegram-bot-ruby#inline-keyboards).

In your case, `message` is a `CallbackQuery` and it doesn't have `message_id` attribute ([spec](https://core.telegram.org/bots/api#callbackquery)), only `inline_message_id`.

**Comment by arn01d** [comment]
Thank for taking this up, and the tip on using **inline_message_id**. 

However, I am confused. This is my test code, and I cannot figure out why this script cannot find the old message to edit!? 

```
Telegram::Bot::Client.run(token) do |bot|
bot.listen do |message|
case message
when  Telegram::Bot::Types::CallbackQuery
      # Here you can handle your callbacks from inline buttons
    if  message.data == 'Old'
        oldkb = [
        Telegram::Bot::Types::InlineKeyboardButton.new(text: 'Get New Message', callback_data: 'New1')
        ]
        oldmarkup = Telegram::Bot::Types::InlineKeyboardMarkup.new(inline_keyboard: oldkb)
        bot.api.send_message(chat_id: message.from.id, text: "This is the old message. The Chat ID is#{message.from.id} and Message ID is #{message.id}", reply_markup: oldmarkup)
    elsif   message.data == 'New1'
            newkb = [
            Telegram::Bot::Types::InlineKeyboardButton.new(text: 'Get Next New Message', callback_data: 'New2')
            ]
            newmarkup = Telegram::Bot::Types::InlineKeyboardMarkup.new(inline_keyboard: newkb)
            bot.api.edit_message_text(chat_id: message.from.id, inline_message_id: message.id, text: 'This is the new message.', reply_markup: newmarkup)
        end

when  Telegram::Bot::Types::Message
          startkb = [
          Telegram::Bot::Types::InlineKeyboardButton.new(text: 'Send Message', callback_data: 'Old')
          ]
          startmarkup = Telegram::Bot::Types::InlineKeyboardMarkup.new(inline_keyboard: startkb)

          bot.api.send_message(chat_id: message.chat.id, text: 'Hello', reply_markup: startmarkup)
      end
    end
end
```

**Comment by arn01d** [comment]
Hi @atipugin. Still working on using the `edit_message_text` method and still getting _"Bad request: message not found"_ error!? You stated:

> In your case, `message` is a `CallbackQuery` and it doesn't have `message_id` attribute (spec), only `inline_message_id`.

However, the  ([spec](https://core.telegram.org/bots/api#callbackquery)) states that there are both `id` and `inline_message_id`. 

When I display contents of the `CallbackQuery` attributes in my `message`; i.e `#{message.from.id}, #{message.id}, #{message.inline_message_id}` There is nothing in `inline_message_id`, only `message.from.id` and `message.id` contain values.

Am I right then, to say that the case of `edit_message_text`, we should be using `chat_id: message.from.id` with `message_id: message.id` and not `inline_message_id: message.inline_message_id` to find and update the old `message`?

**Comment by arn01d** [comment]
Finally got it. Thanks to code snippet I in @celisflen-bers fork of _it-books-bot_ @leocabeza.

I was a bit off. Continue to be a lifelong learner! 

I was supposed to use `message_id: message.message.message_id`  and  `chat_id: message.message.chat.id` to find and update the old message.

Many thanks @atipugin - telegram-bot-ruby rocks!!

**Comment by mm580486** [comment]
i have some problem like you , how to you fix this problem ? 
```
`block (2 levels) in <main>': undefined method `text' for #<Telegram::Bot::Types::CallbackQuery:0x007fe4eb8b3c10> (NoMethodError)
```
