### ISSUE TITLE
I can't connect botan

### ISSUE THREAD

**Issue by SergeyAlekseevN** [atipugin/telegram-bot-ruby#6]
Connected botan as written in the instructions. When you run displays an error:
        
    C:/dev/Ruby22/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)

Here is my code:

    require 'telegram/bot'
    require 'telegram/bot/botan'

    token = 'myBotToken'

    Telegram::Bot::Client.run(token) { |bot|
      bot.enable_botan!('myBotanAPIkey')
      bot.listen { |message|
        case message.text
          when '/start'
            bot.track('Started', message.from.id, type_of_chat: message.chat.class.name)
        end
      }
    }

What did I do wrong?

**Comment by atipugin** [comment]
Seems like Ruby has problems with your SSL certificate. It's not related to this gem. Take a look on this question on SO: https://stackoverflow.com/questions/5711190/how-to-get-rid-of-opensslsslsslerror
