### ISSUE TITLE
How do we pin a message?

### ISSUE THREAD

**Issue by arn01d** [atipugin/telegram-bot-ruby#61]
Hi @atipugin 
Not really an issue, but asking for some advice. How do we pin a message using `pinned_message`.
This is my unsuccessful attempt
`bot.api.send_message(chat_id: message.chat.id, parse_mode: 'html', text: "Message to be pinned", pinned_message: message.message_id)`

**Comment by ivanovaleksey** [comment]
According to [official api](https://core.telegram.org/bots/api#message) `pinned_message` should be `Message` object. But I can't provide you with exact working sample.
