### ISSUE TITLE
Don't work Inline Mode with IPhone 6 client

### ISSUE THREAD

**Issue by mpolev** [atipugin/telegram-bot-ruby#62]
My bot can not accept inline messages from IOS Telegram client. Messages do not arrive. Other bots work in inline mode, for example, @music.
In the same time, with Android Telegram all working.

What can be wrong?
Please, help me

**Comment by ivanovaleksey** [comment]
Hi. Did you try to use pure Telegram Bot API?
It's more likely problem  the client itself.

**Comment by mpolev** [comment]
Hi, ivanovaleksey.
No, I haven't tested. I will try, thanks for help.

**Comment by mpolev** [comment]
The problem was related to the definition of location
