### ISSUE TITLE
Location of user?

### ISSUE THREAD

**Issue by kuzevanoff** [atipugin/telegram-bot-ruby#64]
How i can get location of current user?
Thanks

**Comment by hugonomura** [comment]
If you want know the current location for the user, you need request this to him.
(**in the Android app:** click on clip icon -> Location -> send the location).
You also can create a custom button to send the current location (there is a example on README of the project: https://github.com/atipugin/telegram-bot-ruby/#custom-keyboards)
After the user sent the current location to you, you just need recover this information using:
message.location.latitude - to get the current latitude coordinate
message.location.longitude - to get the current longitude coordinate
If the user sent just a normal text message, you will get a exception when you try access this attributes of the message.

**Comment by ivanovaleksey** [comment]
Hi @kuzevanoff, can you close the issue?
