### ISSUE TITLE
Command with arguments

### ISSUE THREAD

**Issue by JorgeDDW** [atipugin/telegram-bot-ruby#66]
Sorry for my noob question but!

How can i create a command with arguments? example:
`/car Honda
`
and the bot answer a list with all the Honda models?

**Comment by ivanovaleksey** [comment]
I think for bot there are no arguments.
A command is just plain text.
You should parse it manually.

In your particular case you can first grab command name from incoming message. Then remained part of message would be your arguments.

**Comment by JorgeDDW** [comment]
Thanks @ivanovaleksey I got to the answer 💃

**Comment by pranavthombare** [comment]
Can you tell us how?
