### ISSUE TITLE
Emoji in message text

### ISSUE THREAD

**Issue by olegatr** [atipugin/telegram-bot-ruby#67]
Hi,
How can i add emoji to message?
Thanks

**Comment by ivanovaleksey** [comment]
Hi.
One way to do as I know is just send emoji unicode code inside message, i.e.
"\u{1F603} Some text here"

You can pick emoji codes [here](http://apps.timwhitlock.info/unicode/inspect/hex/1F6038)

**Comment by olegatr** [comment]
Thanks

**Comment by mpz** [comment]
Also you can simply use copy&paste to editor: 😱, 😏, etc

**Comment by ivanovaleksey** [comment]
@mpz seems like you have provided the same link ☺️

**Comment by mpz** [comment]
Yes, @ivanovaleksey , i just note about copy&paste
