### ISSUE TITLE
Send file through url instead of upload

### ISSUE THREAD

**Issue by JorgeDDW** [atipugin/telegram-bot-ruby#68]
Hi there,

In my part of learn Ruby, JSON, and Telegram Bots I want to make a Pokedext, and here is what i need to send file through the url i get from the API instead of upload from the server:
`
bot.api.send_photo(chat_id: message.chat.id, photo: Faraday::UploadIO.new('~/Desktop/jennifer.jpg', 'image/jpeg'))`

What do I need to change in order to use a url ?

**Comment by ivanovaleksey** [comment]
Can you send url as plain text, i.e. using `send_message` method?

**Comment by JorgeDDW** [comment]
I could do that, but how ever its more cool if just send the image :(

**Comment by ivanovaleksey** [comment]
I am not sure but try to do this
```
require 'open-uri'
bot.api.send_photo(chat_id: message.chat.id, photo: open(image_url))
```

**Comment by JorgeDDW** [comment]
not working :(
But thanks for trying.

Saludos,
Jorge Dominguez

2016-07-13 8:53 GMT-04:00 Aleksey Ivanov <notifications@github.com>:

**Comment by d4rk5eed** [comment]
@JorgeDDW try `bot.api.send_message(chat_id: message.from.id, text: "<a href=\"http://fonday.ru/images/tmp/16/7/original/16710fBjLzqnJlMXhoFHAG.jpg\">Cats</a>", parse_mode: "HTML" )` , telegram cleint renders image by itself

**Comment by M1chael** [comment]
If your url is http you can post an image just like this:
`telegram.api.send_photo(chat_id: <chat_id>, caption: <text>, photo: <http url>)`
