### ISSUE TITLE
Trying to run the bot gives undefined error message for method 'run'

### ISSUE THREAD

**Issue by Skarlso** [atipugin/telegram-bot-ruby#71]
Hi. So I'm trying to run this example:

```ruby
#!/usr/bin/env ruby
require 'telegram/bot'

token = 'YOUR_TELEGRAM_BOT_API_TOKEN'

Telegram::Bot::Client.run(token) do |bot|
  bot.listen do |message|
    case message.text
    when '/start'
      bot.api.send_message(chat_id: message.chat.id, text: "Hello, #{message.from.first_name}")
    when '/stop'
      bot.api.send_message(chat_id: message.chat.id, text: "Bye, #{message.from.first_name}")
    end
  end
end
```

And this gives me this error message:

```bash
`<main>': undefined method `run' for Telegram::Bot::Client:Class (NoMethodError)
```

I'm using the latest version of the gem.

So..um...what now? :O

If I do it with `new` there is no error. But in that case, the bot isn't working. It immediately returns and that's it. Don't know if it's supposed to, but if I message the bot, nothing happens.

**Comment by ivanovaleksey** [comment]
The latest gem version is `0.5.3`.
At this version `Telegram::Bot::Client` class definitely [has](https://github.com/atipugin/telegram-bot-ruby/blob/v0.5.3/lib/telegram/bot/client.rb#L7-L9) `run` method.

**Comment by atipugin** [comment]
It's there from day one ;)

**Comment by ivanovaleksey** [comment]
Yeah, I know 😊  It is just for the version check.

**Comment by Skarlso** [comment]
Yeah, I know it's there. I can see it. :O But for some reason, it's still saying no cigar. I'm going to run it in a moment.

**Comment by Skarlso** [comment]
Okay, what am I doing incorrectly?

```ruby
require 'telegram/bot'
puts Telegram::Bot::VERSION
```

Output

```bash
test.rb:3:in `<main>': uninitialized constant Telegram::Bot::VERSION (NameError)
```

**Comment by ivanovaleksey** [comment]
Try to run `gem list telegram` and post the output.

**Comment by Skarlso** [comment]
```bash
gem list telegram

*** LOCAL GEMS ***

telegram (0.0.1)
telegram-bot (0.8.0)
telegram-bot-ruby (0.5.3)
telegram_bot (0.0.6)
```

**Comment by ivanovaleksey** [comment]
This is what I thought.
You have another gem (`telegram-bot (0.8.0)`) which [defines](https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/client.rb) `Telegram::Bot::Client` class.
I would recommend you to create `Gemfile` and user bundler to fetch right gem.

```
$ bundle init
$ echo 'telegram-bot-ruby' >> Gemfle
```

Now you can run `bundle exec your-script.rb` and `bundle console`.
If don't know much about bundler check out official docs.

**Comment by Skarlso** [comment]
Yeah, I know bundler. Interesting. Shouldn't it, like, be in its own module, and not interfere with other gems? I'm gonna try that. :)

**Comment by Skarlso** [comment]
Yeah, that worked. 

```bash
bundle console
Resolving dependencies...
 :001 > require 'telegram/bot'
 => true
 :002 > puts Telegram::Bot::VERSION
0.5.3
 => nil
 :003 >
```

**Comment by Skarlso** [comment]
Yepp, with Bundler it does work. :) Thanks for the support man. I'm going to switch to this gem. ;))) Thanks!

**Comment by ivanovaleksey** [comment]
Nice!
Both gems have its own module but it called just the same `Telegram::Bot`.
I don't think one can use then together in one project because it doesn't make any sense.
And using bundler is the best practice all the time!

**Comment by Skarlso** [comment]
That is true. Yeah, I'm not using tham together in one project. :D It was just installed in my main gemlist. :/ So they could knock each other out as I was experimenting around with Telegram. :) 

But this gem is easily more concise. :) And has very nice support. ;))) 

Thanks again!

**Comment by onedebos** [comment]
If anyone is facing this same issue, I found a hacky fix for it. When running this code from my macOS terminal, I get the **undefined method 'run'** message. When I run it inside my vscode terminal on the other hand, it works correctly. I had this same issue on a Linux machine aswell. It probably has something to do with how my environment is setup. 

Hope this helps someone out.

**Comment by yayahc** [comment]
$ sudo gem uninstall telegram-bot
$ sudo gem install telegram-bot-ruby
