### ISSUE TITLE
custome commands!

### ISSUE THREAD

**Issue by MojtabaMonfared** [atipugin/telegram-bot-ruby#74]
hi everyone :heart: 
i want to give custom commands from user like `/echo Hello` or anything like this
i tried to use `split()` method but i fail :disappointed: 
who can write sample code for me?
i am beginner :confused: 
thanks

**Comment by ivanovaleksey** [comment]
Hi. Like on StackOverflow you better show the code that you got so far.
It would be more efficient.

**Comment by MojtabaMonfared** [comment]
i tired for read any doc
could you help me to write that? please

**Comment by ivanovaleksey** [comment]
No. There is absolutely perfect example in [README](https://github.com/atipugin/telegram-bot-ruby#usage).

**Comment by MojtabaMonfared** [comment]
# oh men
i just want to learn
i want to get dynamic commands from user
in README writes only one commands like _/start_ or _/end_

**Comment by Defman21** [comment]
Just use regex then.

```
if message.text =~ %r(^/echo\s(.+)$)
  echo = %r(^/echo\s(.+)$).match(message.text).captures[0]
  bot.api.send_message chat_id: message.from.id,
                               text: echo,
                               parse_mode: "Markdown"
```

**Comment by ivanovaleksey** [comment]
Seems like this one can be closed.
