### ISSUE TITLE
How do i create horizontal InlineKeyboardMarkup using  InlineKeyboardButton

### ISSUE THREAD

**Issue by leoamigood** [atipugin/telegram-bot-ruby#77]
I cant figure out how to create horizontal markup

```
      kb = %w(easy medium hard).reduce([]) { |kb, level|
        kb << Telegram::Bot::Types::InlineKeyboardButton.new(text: level, callback_data: "/level #{level}")
      }
      markup = Telegram::Bot::Types::InlineKeyboardMarkup.new(inline_keyboard: kb)
```

gives me vertically arranged buttons. 

Please suggest,
Leo

**Comment by ivanovaleksey** [comment]
Hi @leoamigood 
With `reduce` like that (by the way you can just use `map` in this case) you get
```
kb = [
  button-for-easy,
  button-for-medium,
  button-for-hard
]
```
So there is no any error that it gives you vertical markup.

Also avoid shadowing local variable by block variable by using the same names
`kb = ... { |kb, level|`. It would be much cleaner to use `kb = ... do |memo, level|`.

To get horizontal markup you need `kb` variable to be the first element of another array. 
For example
```
markup = Telegram::Bot::Types::InlineKeyboardMarkup.new(inline_keyboard: [kb])
```

Or you can define `kb` like that:
```
kb = %w(easy medium hard).each_with_object([[]]) do |level, memo|
  memo.first << level
end
```

**Comment by leoamigood** [comment]
Works! Thank you for the explanation.
