### ISSUE TITLE
Heroku apps crashing

### ISSUE THREAD

**Issue by kalashnikovisme** [atipugin/telegram-bot-ruby#78]
I've added this code to intializer

```ruby
require 'telegram/bot'

token = ENV['TELEGRAM_TOKEN']

Telegram::Bot::Client.run(token) do |bot|
  bot.listen do |message|
    case message.text
    when '/start'
      bot.api.send_message(chat_id: message.chat.id, text: "Hello, #{message.from.first_name}")
    when '/stop'
      bot.api.send_message(chat_id: message.chat.id, text: "Bye, #{message.from.first_name}")
    end
  end
end
```

And have this error

```
at=error code=H10 desc="App crashed" method=GET path="/" host=karamzin.herokuapp.com request_id=a7d594e7-8cc8-483c-a8f4-2514bfc074bd fwd="79.132.126.168" dyno= connect= service= status=503 bytes=
```

Bot is working during this time. I think that it's memory problems on heroku. But I'm not sure.

**Comment by atipugin** [comment]
You mean your rails app initializer?)

**Comment by kalashnikovisme** [comment]
@atipugin yes.
Problem was solved.
I've added this code to rake task and I've added rake task to Heroku Scheduler.

I think it should be closed.

**Comment by kalashnikovisme** [comment]
It's fun!

I've tried to run this in the Rails initializer almost four years later... And found this solution, again!

I think, I'm unteachable

**Comment by ivanovaleksey** [comment]
This time you will remember it :)
