### ISSUE TITLE
set_webhook with certificate param

### ISSUE THREAD

**Issue by ssnake** [atipugin/telegram-bot-ruby#79]
If use self-signed certificate and try to set web hook with following code:
`bot.api.set_webhook url: hook_url, certificate: File.open('telegram.pem')` Things do not work. It doesn't upload certificate.

**Comment by ivanovaleksey** [comment]
It is said [here](https://core.telegram.org/bots/api/#setwebhook) that `certificate` should be instance of `InputFile`. 
I am not sure if the gem supports this type. I'll try to check it.

**Comment by ssnake** [comment]
Such method of setting webhook I took from here https://github.com/solyaris/BOTServer/blob/master/lib/webhook.rb#L48
I found solution:
`curl -F "url=https://<HOSTNAME>/webhooks/telegram" -F "certificate=@<FULL_PATH_TO_CERT.pem" https://api.telegram.org/bot<BOT_TOKEN>/setWebhook`
So I wonder if it's possible to set webhook via this gem.

**Comment by atipugin** [comment]
You can use `certificatite: Faraday::UploadIO.new('/path/to/cert')` param for `set_webhook` method (see here: https://core.telegram.org/bots/api#setwebhook).

**Comment by solyaris** [comment]
and see also Telegram Platfporm Bot API 2.3.1 
[Marvin's Marvellous Guide to All Things Webhook](doc: https://core.telegram.org/bots/webhooks)

BTW, Thanks Alexander for your work!

**Comment by solyarisoftware** [comment]
please take open the issue
