### ISSUE TITLE
code example not working

### ISSUE THREAD

**Issue by thibauld** [atipugin/telegram-bot-ruby#8]
I wanted to play with your ruby wrapper for telegram's bot api so I created a new telegram bot, copy/pasted one of your code example (https://github.com/democratech/bot) but when I run the code, I get the following error:
```
$ bundle exec ruby bot.rb
/var/lib/gems/1.9.1/gems/httparty-0.13.5/lib/httparty/response.rb:71:in `method_missing': undefined method `to_h' for #<HTTParty::Response:0x00000001e481c0> (NoMethodError)
	from /var/lib/gems/1.9.1/gems/telegram-bot-ruby-0.3.1/lib/telegram/bot/api.rb:34:in `call'
	from /var/lib/gems/1.9.1/gems/telegram-bot-ruby-0.3.1/lib/telegram/bot/api.rb:27:in `method_missing'
	from /var/lib/gems/1.9.1/gems/telegram-bot-ruby-0.3.1/lib/telegram/bot/client.rb:27:in `block in listen'
	from /var/lib/gems/1.9.1/gems/telegram-bot-ruby-0.3.1/lib/telegram/bot/client.rb:26:in `loop'
	from /var/lib/gems/1.9.1/gems/telegram-bot-ruby-0.3.1/lib/telegram/bot/client.rb:26:in `listen'
	from bot.rb:5:in `block in <main>'
	from /var/lib/gems/1.9.1/gems/telegram-bot-ruby-0.3.1/lib/telegram/bot/client.rb:22:in `run'
	from /var/lib/gems/1.9.1/gems/telegram-bot-ruby-0.3.1/lib/telegram/bot/client.rb:10:in `run'
	from bot.rb:4:in `<main>'
```

Am I doing something wrong here ? It would be good to add a section in your README.md to guide people on how to have a fully working example running on their machine.

**Comment by atipugin** [comment]
@thibauld example is fully working. Problem was with HTTParty - it suddenly stopped responding to `#to_h` method (i still can't figure out why). 

Anyway, i've fixed this problem and everything should be fine now. Please update gem up to 0.3.2 and let me know if your problem is solved.

**Comment by thibauld** [comment]
works like a charm now, thanks for your impressive reactivity!

**Comment by atipugin** [comment]
You're welcome :+1:
