### ISSUE TITLE
Add support for ReplyKeyboardRemove type

### ISSUE THREAD

**Issue by ivanovaleksey** [atipugin/telegram-bot-ruby#81]
Hi @atipugin!

I'd like to thank you once again for the great gem.

I always had some misunderstanding of how hiding custom keyboards works. And recently I have noticed that bot API have new [`ReplyKeyboardRemove`](https://core.telegram.org/bots/api#replykeyboardremove) type.
It seems like the gem doesn't support it yet. It also seems like existing [`ReplyKeyboardHide`](https://github.com/atipugin/telegram-bot-ruby/blob/master/lib/telegram/bot/types/reply_keyboard_hide.rb) type is outdated since it is not described in the docs.

If I am not missing anything we should add support for `ReplyKeyboardRemove` and remove `ReplyKeyboardHide` type, shouldn't we?

If it is so can I try to create PR?

Thank you.

**Comment by atipugin** [comment]
Hi! Yes, looks like they changed `ReplyKeyboardHide` to `ReplyKeyboardRemove` and didn't even mentioned it in the changelog. Feel free to make a PR ;)

**Comment by cippaciong** [comment]
They finally announced it in [Bot API 2.3](https://core.telegram.org/bots/api-changelog#november-21-2016) .

**Comment by ivanovaleksey** [comment]
Thank you for the information @cippaciong.
Seems like there are other things to do :relaxed:
