### ISSUE TITLE
Support ChannelPosts

### ISSUE THREAD

**Issue by oscillot** [atipugin/telegram-bot-ruby#82]
While spinning up a new bot somebody sent the bot a command from the channel being used for announcement. The gem did not handle this well:

```
Users/foo/.rvm/gems/ruby-2.3.0/gems/telegram-bot-ruby-0.6.0.2/lib/telegram/bot/client.rb:61:in `log_incoming_message': undefined method `from' for nil:NilClass (NoMethodError)
  from /Users/foo/.rvm/gems/ruby-2.3.0/gems/telegram-bot-ruby-0.6.0.2/lib/telegram/bot/client.rb:39:in `block in fetch_updates'
  from /Users/foo/.rvm/gems/ruby-2.3.0/gems/telegram-bot-ruby-0.6.0.2/lib/telegram/bot/client.rb:35:in `each'
  from /Users/foo/.rvm/gems/ruby-2.3.0/gems/telegram-bot-ruby-0.6.0.2/lib/telegram/bot/client.rb:35:in `fetch_updates'
  from /Users/foo/.rvm/gems/ruby-2.3.0/gems/telegram-bot-ruby-0.6.0.2/lib/telegram/bot/client.rb:27:in `listen'
  from start_league_bot.rb:13:in `block in <main>'
  from /Users/foo/.rvm/gems/ruby-2.3.0/gems/telegram-bot-ruby-0.6.0.2/lib/telegram/bot/client.rb:20:in `run'
  from /Users/foo/.rvm/gems/ruby-2.3.0/gems/telegram-bot-ruby-0.6.0.2/lib/telegram/bot/client.rb:8:in `run'
  from start_bot.rb:12:in `<main>'
```

start_bot looks just like the example and line 12 was `bot.listen do |message|`

Stepping through with pry I saw that the Update object wasn't being created successfully. Update expects a number of possible message types, such as 'message' (which is what i'm used to seeing) 'inline_query', 'callback_query', 'chosen_inline_result', etc. What's not expected is what we have, which is the key 'channel_post'. I tried some monkey patching to make it behave like a Message but the shape wasn't quite right. In the end I went with this:

```
require 'telegram/bot/client'
require 'telegram/bot/types/update'
require 'faraday/error'

class Telegram::Bot::Client
  def fetch_updates
    response = api.getUpdates(offset: offset, timeout: timeout)
    return unless response['ok']

    response['result'].each do |data|
      update = Telegram::Bot::Types::Update.new(data)
      @offset = update.update_id.next
      message = extract_message(update)
      return unless message
      log_incoming_message(message)
      yield message
    end
  rescue Faraday::Error::TimeoutError
    retry
  end
end
```

Which has the effect of ignoring any type of Message that the gem doesn't parse correctly. Hilariously once you have processed the message, you don't actually need the monkeypatch any longer, so long as you don't send any more ChannelPosts through the bot.

**Comment by ivanovaleksey** [comment]
`Types::Update` now can [have]( https://core.telegram.org/bots/api#update) fields: `channel_post`, `edited_channel_post`.

**Comment by ivanovaleksey** [comment]
Hi @oscillot 
Can you try to update the gem and reproduce the error?
