### ISSUE TITLE
InlineKeyboardMarkup#to_compact_hash change initial object

### ISSUE THREAD

**Issue by ivanovaleksey** [atipugin/telegram-bot-ruby#92]
Hi @atipugin!

I am not sure is it an issue really.
So I'd like to know your thoughts about it.

Given the following code 
```
keyboard = [
  Telegram::Bot::Types::InlineKeyboardButton.new(text: 'Button 1', callback_data: 'first_btn'),
  Telegram::Bot::Types::InlineKeyboardButton.new(text: 'Button 2', callback_data: 'second_btn')
]
markup = Telegram::Bot::Types::InlineKeyboardMarkup.new(inline_keyboard: keyboard)

BOT.api.send_message chat_id: ..., text: 'Foo', reply_markup: markup
```

Before `send_message` call `markup` object is 
```
#<Telegram::Bot::Types::InlineKeyboardMarkup:0x007f87962a2068 @inline_keyboard=[[#<Telegram::Bot::Types::InlineKeyboardButton:0x007f87962c31f0 @text="Button 1", @callback_data="first_btn", @url=nil, @switch_inline_query=nil, @switch_inline_query_current_chat=nil, @callback_game=nil>], [#<Telegram::Bot::Types::InlineKeyboardButton:0x007f87962ba438 @text="Button 2", @callback_data="second_btn", @url=nil, @switch_inline_query=nil, @switch_inline_query_current_chat=nil, @callback_game=nil>]]>
```
So `markup.inline_keyboard` is really `Array[Array[InlineKeyboardButton]]` as it described in [`Types::InlineKeyboardButton`](https://github.com/atipugin/telegram-bot-ruby/blob/master/lib/telegram/bot/types/inline_keyboard_markup.rb#L5).

But after `send_message` call `markup` object is 
```
#<Telegram::Bot::Types::InlineKeyboardMarkup:0x007f87962a2068 @inline_keyboard=[[{:text=>"Button 1", :callback_data=>"first_btn"}], [{:text=>"Button 2", :callback_data=>"second_btn"}]]>
```
So `markup.inline_keyboard` is `Array[Array[Hash]]`.

It happens because of `map!` [here](https://github.com/atipugin/telegram-bot-ruby/blob/master/lib/telegram/bot/types/inline_keyboard_markup.rb#L9).

On one hand it seems to be bad to modify the outter `markup` object. But on the other hand it may be considered as an optimization for next calls.

Is it done intentionally and should not be touched?

**Comment by ivanovaleksey** [comment]
Hi @atipugin, could you please take a look?

**Comment by atipugin** [comment]
@ivanovaleksey hey! I agree, it shouldn't behave this way. Need to be improved

**Comment by ivanovaleksey** [comment]
If you don't mind I will provide a PR.

**Comment by atipugin** [comment]
It would be great!
