### ISSUE TITLE
Best way to handle a crash?

### ISSUE THREAD

**Issue by pparamalingam** [atipugin/telegram-bot-ruby#94]
Is there any recommended framework to use on top of this to restart the bot on a crash?

How would one typically handle a network exception such as connection reset? Is there a way to invoke the bot library to restart polling or does it have to be handled on the server level to restart the Ruby script?

Not really an issue per say just looking for best practice to keep the bot highly available automatically

**Comment by cippaciong** [comment]
You should catch the exception with a `begin/rescue` block and decide how to handle it depending on your necessity.

If you are new to exceptions handling [this article](http://blog.honeybadger.io/a-beginner-s-guide-to-exceptions-in-ruby/) might be helpful (just one out of many if you want to google it).

**Comment by pparamalingam** [comment]
Yup that is how I am doing it now, just curious on how others maintain a production level bot using the ruby library.

**Comment by cippaciong** [comment]
I think that handling exceptions in ruby is the right way to restart the bot (or just avoid the crash) after an expected error.

If you are interested in other cases like restoring after an external error (at the OS level) or an unexpected reboot, I think you should go with initscripts or systemd services (assuming you are using linux or similar to host the bot).

**Comment by ivanovaleksey** [comment]
Hi @pparamalingam, can you close the issue?

**Comment by pparamalingam** [comment]
@ivanovaleksey Done
