### ISSUE TITLE
implement parse_mode

### ISSUE THREAD

**Issue by Stormcore** [atipugin/telegram-bot-ruby#99]
```
bot.api.send_message(parse_mode: 'Markdown',
                           chat_id: ***,
                           text: "*#{course_name}:* #{lead_name} #{lead_phone}, #{lead_mail} [#{lead_url}](#{lead_url})")
```

https://core.telegram.org/bots/api#formatting-options

Thanks a lot for your awesome gem!

**Comment by ivanovaleksey** [comment]
Is something wrong with the `send_message` method?

**Comment by Stormcore** [comment]
seems like this argument is not passed

**Comment by ivanovaleksey** [comment]
Please format your code using ``` to multiline code. 

A quote crom README
> Note that bot.api object implements Telegram Bot API methods as is.

**Comment by Stormcore** [comment]
fixed first message, anyway, did anyone get this working?

**Comment by Stormcore** [comment]
Here is my console report:
```
{
        "ok" => true,
    "result" => {
        "message_id" => 24,
              "from" => {
                    "id" => ***,
            "first_name" => "*** LEADS",
              "username" => "imprium_leads_bot"
        },
              "chat" => {
                                        "id" => -***,
                                     "title" => "***-LEADS",
                                      "type" => "group",
            "all_members_are_administrators" => true
        },
              "date" => ***,
              "text" => "-: qweqwe ***, qweqw@df.ff http://localhost:3000/leads/9",
          "entities" => [
            [0] {
                  "type" => "bold",
                "offset" => 0,
                "length" => 2
            },
            [1] {
                  "type" => "email",
                "offset" => 27,
                "length" => 11
            }
        ]
    }
}
"Sent Successfully"

```

**Comment by ivanovaleksey** [comment]
Yes, it works for me. 
If you want to get bold text you should use **, like **that**.

**Comment by ivanovaleksey** [comment]
Seems like you represent your link not with text but with url, you got `lead_url` in both places.

**Comment by Stormcore** [comment]
That is my intention indeed! However, changing url in square brackets to text does not help

**Comment by ivanovaleksey** [comment]
It is definitely something wrong with you markdown. 
Please provide interpolated message, i. e. what the result message text is?

**Comment by Stormcore** [comment]
![screen shot 2017-01-15 at 22 34 43](https://cloud.githubusercontent.com/assets/2528948/21965527/ed8fcf90-db72-11e6-991f-daaca1077ade.png)

**Comment by ivanovaleksey** [comment]
I mean message text as is not screenshot. You can add some `puts` to see it or get from your log (if there is one)
We should take a look at what message text is after all interpolations.

**Comment by Stormcore** [comment]
```
{
        "ok" => true,
    "result" => {
        "message_id" => 26,
              "from" => {
                    "id" => ***,
            "first_name" => "LEADS",
              "username" => "imprium_leads_bot"
        },
              "chat" => {
                                        "id" => -****,
                                     "title" => "LEADS",
                                      "type" => "group",
            "all_members_are_administrators" => true
        },
              "date" => 1484508512,
              "text" => "-: qweqwe 11112312312312, qweqw@df.ff qqq",
          "entities" => [
            [0] {
                  **"type" => "bold"**,
                "offset" => 0,
                "length" => 2
            },
            [1] {
                  "type" => "email",
                "offset" => 26,
                "length" => 11
            }
        ]
    }
}

```

**Comment by ivanovaleksey** [comment]
Have you read my message? I wrote: "text after interpolations", not Telegram response. 
Have you tried to use ** instead of *?

**Comment by Stormcore** [comment]
yes, I tried, same result

**Comment by Stormcore** [comment]
ok, I see, text after interpolation, will send

**Comment by Stormcore** [comment]
"*-:* qweqwe 123123123123, qweqw@df.ff [http://localhost:3000/leads/12](http://localhost:3000/leads/12)"

**Comment by Stormcore** [comment]
```
 "entities" => [
            [0] {
                  "type" => "bold",
                "offset" => 0,
                "length" => 2
```
clearly tells that bold node was processed

**Comment by ivanovaleksey** [comment]
Thanks, yes. Anyway it has nothing to do with the gem since it only forwards given parameters to Telegram API. 
Maybe something wrong with markdown in group chats.

**Comment by Stormcore** [comment]
seems so

**Comment by ivanovaleksey** [comment]
@Stormcore a good news for you ☺️ 

You just got very very bad debug example. **-:** is indeed bold but it's very hard to see.
I checked it with another string - everything works fine both group and private chats.

```
bot.api.send_message(
  chat_id: message.chat.id,
  text: "*bold text* and plain text",
  parse_mode: 'Markdown'
)
```

**Comment by Stormcore** [comment]
ahaha, thanks!
